"""Golden parity fixtures (spec §10.2): chatbook engine output must equal
server engine output byte-for-byte on the fixed corpus, with production
sanitization (no test-mode relaxation).

The golden JSON files are generated by Tests/Chunking/golden/generate_golden.py
from the vendored engine with test mode explicitly disabled. The vendored tree
is the server engine byte-for-byte modulo mechanical import rewrites (see the
generation script's docstring), so equality against these files is the
production-path parity evidence. Re-run generation at every
sync_chunking_engine.py execution.

Cross-method combinations that legitimately raise (e.g. the `json` method on
prose) are recorded as deterministic error outcomes; the test asserts the
same error type, not a skip.
"""
import json
from pathlib import Path

import pytest

from Tests.Chunking.conftest import requires_cached_hf_tokenizer

GOLDEN = Path(__file__).parent / "golden"
CORPUS = {
    "prose": "The quick brown fox jumps over the lazy dog. " * 20,
    "markdown_atx": "# Title\n\n## Section A\n\nPara one.\n\n## Section B\n\nPara two.\n",
    "ebook": "# Chapter 1\n\nFirst chapter text.\n\n# Chapter 2\n\nSecond chapter text.\n",
    "json": '{"data": [' + ", ".join(f'{{"item": {i}, "text": "value {i}"}}' for i in range(20)) + ']}',
    "xml": "<root>" + "".join(f"<item id='{i}'>text {i}</item>" for i in range(20)) + "</root>",
    "code": "def f%d():\n    return %d\n" * 10,
    "cjk": "这是一段中文文本。" * 10,
}
METHODS = ["words", "sentences", "paragraphs", "tokens", "json", "xml",
           "ebook_chapters", "structure_aware", "code", "fixed_size"]


# The 'tokens' method resolves the real gpt2 tokenizer from the HF hub.
# Generation (outside pytest, real HOME) uses the locally cached tokenizer;
# under pytest, Tests/conftest.py redirects HOME to a temp dir and the network
# guard blocks the hub download, so the tokens fixtures can only be verified
# where the tokenizer is visible to the test process. The remaining 63
# fixtures (all non-LLM methods that need no tokenizer) are the primary
# parity evidence per spec §10.2.
def _needs_tokenizer(method: str) -> bool:
    return method == "tokens"


def _tokens_available() -> bool:
    return requires_cached_hf_tokenizer()


@pytest.fixture(params=METHODS)
def method(request):
    if _needs_tokenizer(request.param) and not _tokens_available():
        pytest.skip(
            "tokens fixtures need the gpt2 tokenizer visible under pytest's "
            "redirected HOME (HF download blocked by network guard)"
        )
    return request.param


@pytest.mark.parametrize("corpus_key", list(CORPUS))
@pytest.mark.production_path
def test_golden_parity(corpus_key, method):
    from tldw_chatbook.Chunking.engine import Chunker, ChunkerConfig

    chunker = Chunker(ChunkerConfig())
    golden_path = GOLDEN / f"{corpus_key}_{method}.json"
    if not golden_path.exists():
        pytest.skip("golden file not generated yet — run generation script")
    expected = json.loads(golden_path.read_text())

    if expected["outcome"] == "error":
        with pytest.raises(Exception) as excinfo:
            chunker.process_text(
                CORPUS[corpus_key],
                {"method": method, "max_size": 50, "overlap": 10},
            )
        assert type(excinfo.value).__name__ == expected["error_type"]
    else:
        result = chunker.process_text(
            CORPUS[corpus_key],
            {"method": method, "max_size": 50, "overlap": 10},
        )
        assert result == expected["chunks"]
