# Configuration for tldw-cli TUI App
# Located at: ~/.config/tldw_cli/config.toml
[general]
default_tab = "chat"  # "chat", "character", "logs", "media", "search", "ingest", "stats"
default_theme = "textual-dark"  # Default theme on startup ("textual-dark", "textual-light", or any theme name from themes.py)
palette_theme_limit = 1  # Maximum number of themes to show in command palette (0 = show all)
log_level = "INFO" # TUI Log Level: DEBUG, INFO, WARNING, ERROR, CRITICAL
users_name = "default_user" # Default user name for the TUI
use_dropdown_navigation = false  # Use dropdown navigation instead of tab bar

[tldw_api]
base_url = "http://127.0.0.1:8000" # Or your actual default remote endpoint
# Default auth token can be stored here, or leave empty if user must always provide
auth_token = "default-secret-key-for-single-user"

[splash_screen]
# Splash screen configuration for startup animations
enabled = true  # Enable/disable splash screen
duration = 1.5  # Duration in seconds to display splash screen
skip_on_keypress = true  # Allow users to skip with any keypress

# Card selection mode:
# - "random": Randomly selects from active_cards list (default)
# - "sequential": Cycles through active_cards in order (not yet implemented)
# - "<card_name>": Always use a specific card (e.g., "matrix", "glitch", etc.)
card_selection = "random"

show_progress = true  # Show initialization progress bar

# All available splash cards are enabled by default for variety
# To customize: Remove cards you don't want, or replace the entire list with your preferred cards
# Static cards: default, classic, compact, minimal, blueprint
# Animated cards: matrix, glitch, retro, tech_pulse, code_scroll, minimal_fade, arcade_high_score,
#                digital_rain, loading_bar, starfield, terminal_boot, glitch_reveal, ascii_morph,
#                game_of_life, scrolling_credits, spotlight_reveal, sound_bars, raindrops_pond,
#                pixel_zoom, text_explosion, old_film, maze_generator, dwarf_fortress
active_cards = [
    "default", "matrix", "glitch", "retro", "classic", "compact", "minimal",
    "tech_pulse", "code_scroll", "minimal_fade", "blueprint", "arcade_high_score",
    "digital_rain", "loading_bar", "starfield", "terminal_boot", "glitch_reveal",
    "ascii_morph", "game_of_life", "scrolling_credits", "spotlight_reveal", "sound_bars",
    "raindrops_pond", "pixel_zoom", "text_explosion", "old_film", "maze_generator",
    "dwarf_fortress"
]

[splash_screen.effects]
# Animation effect settings
fade_in_duration = 0.3  # Fade in time in seconds
fade_out_duration = 0.2  # Fade out time in seconds
animation_speed = 1.0  # Animation playback speed multiplier

[api_settings]
# API endpoint configuration
# Each API provider can have its own configuration
# Format: [api_settings.<provider>]
#
# Refer to example configuration below and also to the default example config at:
# https://github.com/rmusser01/tldw/blob/dev/Config_Files/config.txt

[api_settings.openai]
api_key = ""
model = "gpt-4o-2024-11-20"
temperature = 0.7
max_tokens = 4096

# [api_settings.anthropic]
# api_key = ""
# model = "claude-3-5-sonnet-20241022"
# temperature = 0.7
# max_tokens = 4096

# [api_settings.moonshot]
# api_key = ""
# model = "kimi-latest"  # Options: kimi-latest, kimi-thinking-preview, moonshot-v1-auto, moonshot-v1-8k, moonshot-v1-32k, moonshot-v1-128k, moonshot-v1-8k-vision-preview, moonshot-v1-32k-vision-preview, moonshot-v1-128k-vision-preview, kimi-k2-0711-preview
# temperature = 0.7
# max_tokens = 4096
# api_region = "international"  # Options: "international" or "china"

# [api_settings.zai]
# api_key = ""
# model = "glm-4.5-flash"  # Options: glm-4.5, glm-4.5-air, glm-4.5-x, glm-4.5-airx, glm-4.5-flash, glm-4-32b-0414-128k
# temperature = 0.7
# max_tokens = 4096
# api_base_url = "https://api.z.ai/api/paas/v4"
# streaming = true

# --- Add other API providers as needed ---

[providers]
# List of available LLM providers and their models
OpenAI = ["gpt-4o-2024-11-20", "gpt-4o-mini-2024-07-18", "gpt-4-turbo", "gpt-3.5-turbo"]
Anthropic = ["claude-3-5-sonnet-20241022", "claude-3-opus-20240229", "claude-3-sonnet-20240229", "claude-3-haiku-20240307"]
Moonshot = ["kimi-latest", "kimi-thinking-preview", "moonshot-v1-auto", "moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"]
Zai = ["glm-4.5", "glm-4.5-air", "glm-4.5-x", "glm-4.5-airx", "glm-4.5-flash", "glm-4-32b-0414-128k"]
Local = ["llama3", "mixtral", "codellama"]

[chat_defaults]
system_message = ""
provider = "openai"  # Default provider for new chats
model = ""  # Leave empty to use provider's default
temperature = 0.7
max_tokens = 4096
api_endpoint = ""

[character_defaults]
# Default settings for new character cards
version = "v3"
creator = ""
tags = []

[database]
# Database file paths (relative to user data directory)
prompts_db = "prompts.db"
rag_qa_db = "rag_qa.db"
character_chat_db = "chatDB.db"

[logging]
# Logging configuration
log_file = "chatbook.log"
file_log_level = "INFO"  # File logging level
console_log_level = "WARNING"  # Console/TUI logging level (for stderr)
log_format = "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{line} - {message}"
log_rotation = "10 MB"  # Rotate when file reaches this size
log_retention = "7 days"  # Keep logs for this duration
log_compression = "zip"  # Compress rotated logs

[notes]
# Notes feature settings
auto_save_enabled = true
auto_save_interval = 300  # seconds
sync_with_filesystem = true
default_template = ""

[themes]
# Custom theme definitions
# You can define your own themes here
# Example:
# [themes.my_custom_theme]
# primary = "#FF6B6B"
# secondary = "#4ECDC4"
# warning = "#FFE66D"
# error = "#FF6B6B"
# success = "#95E1D3"
# accent = "#C7CEEA"
# background = "#2D3436"
# surface = "#34495E"
# panel = "#2C3E50"
# dark = true

[encryption]
# Config file encryption settings (managed by the app)
enabled = false

# --- TTS Settings ---
[TTSSettings]
default_tts_provider = "kokoro"  # Options: "openai", "kokoro", "elevenlabs", "chatterbox", "alltalk", "higgs"
default_tts_voice = "af_sky"  # Default voice for TTS
ALLTALK_TTS_URL_DEFAULT = "http://127.0.0.1:7851"
ALLTALK_TTS_VOICE_DEFAULT = "female_01.wav"
ALLTALK_TTS_LANGUAGE_DEFAULT = "en"
ALLTALK_TTS_OUTPUT_FORMAT_DEFAULT = "wav"

KOKORO_TTS_MODEL_DEFAULT = "kokoro-v0_19.onnx"
KOKORO_ONNX_MODELS_PATH_DEFAULT = "~/.config/tldw_cli/models/kokoro"
KOKORO_ONNX_VOICES_JSON_DEFAULT = "~/.config/tldw_cli/models/kokoro/voices.json"
KOKORO_DEVICE_DEFAULT = "cpu"  # Options: "cpu", "cuda", "cuda:0"
KOKORO_MAX_TOKENS = 500        # Maximum tokens per chunk
KOKORO_ENABLE_VOICE_MIXING = false  # Enable voice mixing feature
KOKORO_TRACK_PERFORMANCE = true     # Track performance metrics

# ElevenLabs TTS settings  
ELEVENLABS_API_KEY_fallback = ""  # Fallback if not in environment
ELEVENLABS_DEFAULT_VOICE = "21m00Tcm4TlvDq8ikWAM"  # Rachel voice ID
ELEVENLABS_DEFAULT_MODEL = "eleven_multilingual_v2"  # Options: eleven_multilingual_v2, eleven_turbo_v2
ELEVENLABS_OUTPUT_FORMAT = "mp3_44100_192"  # High quality MP3
ELEVENLABS_VOICE_STABILITY = 0.5    # Voice consistency (0.0-1.0)
ELEVENLABS_SIMILARITY_BOOST = 0.8   # Voice clarity (0.0-1.0)
ELEVENLABS_STYLE = 0.0              # Style exaggeration (0.0-1.0)
ELEVENLABS_USE_SPEAKER_BOOST = true # Enhanced speaker clarity

# Chatterbox TTS settings
CHATTERBOX_DEVICE = "cpu"  # Options: "cpu", "cuda"
CHATTERBOX_VOICE_DIR = "~/.config/tldw_cli/chatterbox_voices"
CHATTERBOX_EXAGGERATION = 0.5     # Emotion exaggeration (0.0-1.0)
CHATTERBOX_CFG_WEIGHT = 0.5       # CFG weight (0.0-1.0)
CHATTERBOX_TEMPERATURE = 0.5      # Generation temperature (0.0-2.0)
CHATTERBOX_CHUNK_SIZE = 1024      # Audio chunk size
CHATTERBOX_NUM_CANDIDATES = 1     # Number of candidates (1-5)
CHATTERBOX_VALIDATE_WHISPER = false  # Enable Whisper validation
CHATTERBOX_PREPROCESS_TEXT = true    # Enable text preprocessing
CHATTERBOX_NORMALIZE_AUDIO = true    # Enable audio normalization
CHATTERBOX_TARGET_DB = -20.0         # Target dB level (-40 to 0)
CHATTERBOX_MAX_CHUNK_SIZE = 500      # Max text chunk size
CHATTERBOX_STREAMING = true          # Enable streaming
CHATTERBOX_STREAM_CHUNK_SIZE = 4096  # Stream chunk size
CHATTERBOX_ENABLE_CROSSFADE = true   # Enable crossfade
CHATTERBOX_CROSSFADE_MS = 50         # Crossfade duration (ms)

# OpenAI TTS settings
OPENAI_BASE_URL = "https://api.openai.com/v1/audio/speech"  # Custom API endpoint
OPENAI_ORG_ID = ""  # Organization ID (optional)

# Higgs Audio TTS settings
HIGGS_MODEL_PATH = "bosonai/higgs-audio-v2-generation-3B-base"  # Model identifier or local path
HIGGS_DEVICE = "auto"  # Options: "auto", "cpu", "cuda", "cuda:0" (auto detects CUDA availability)
HIGGS_ENABLE_FLASH_ATTN = true  # Enable flash attention optimization
HIGGS_DTYPE = "bfloat16"  # Options: "float32", "float16", "bfloat16"
HIGGS_VOICE_SAMPLES_DIR = "~/.config/tldw_cli/higgs_voices"  # Voice profile storage
HIGGS_ENABLE_VOICE_CLONING = true  # Enable zero-shot voice cloning
HIGGS_MAX_REFERENCE_DURATION = 30  # Maximum reference audio duration in seconds
HIGGS_DEFAULT_LANGUAGE = "en"  # Default language code
HIGGS_ENABLE_BACKGROUND_MUSIC = false  # Enable background music mixing
HIGGS_ENABLE_MULTI_SPEAKER = true  # Enable multi-speaker dialog generation
HIGGS_SPEAKER_DELIMITER = "|||"  # Delimiter for speaker changes
HIGGS_MAX_TOKENS = 500  # Maximum tokens per chunk
HIGGS_TRACK_PERFORMANCE = true  # Track performance metrics

# Higgs Audio generation parameters
HIGGS_MAX_NEW_TOKENS = 4096  # Maximum tokens to generate
HIGGS_TEMPERATURE = 0.7  # Sampling temperature (0.0-2.0)
HIGGS_TOP_P = 0.9  # Nucleus sampling (0.0-1.0)
HIGGS_REPETITION_PENALTY = 1.1  # Repetition penalty (1.0 = no penalty)

# --- STT Settings ---
[STTSettings]
# Default Speech-to-Text provider
# Options: "faster-whisper", "qwen2audio", "parakeet", "canary", "parakeet-mlx", "lightning-whisper-mlx"
# Note: On macOS, automatically defaults to parakeet-mlx or lightning-whisper-mlx if available
default_stt_provider = "faster-whisper"

# --- Search Settings ---
# [search_settings]
# default_provider = "google"
# ...