# Configuration for tldw-cli TUI App
# Located at: ~/.config/tldw_cli/config.toml
[general]
default_tab = "chat"  # "chat", "character", "logs", "media", "search", "ingest", "stats"
default_theme = "textual-dark"  # Default theme on startup ("textual-dark", "textual-light", or any theme name from themes.py)
palette_theme_limit = 1  # Maximum number of themes to show in command palette (0 = show all)
log_level = "INFO" # TUI Log Level: DEBUG, INFO, WARNING, ERROR, CRITICAL
users_name = "default_user" # Default user name for the TUI

[tldw_api]
base_url = "http://127.0.0.1:8000" # Or your actual default remote endpoint
# Default auth token can be stored here, or leave empty if user must always provide
auth_token = "default-secret-key-for-single-user"

[splash_screen]
# Splash screen configuration for startup animations
enabled = true  # Enable/disable splash screen
duration = 1.5  # Duration in seconds to display splash screen
skip_on_keypress = true  # Allow users to skip with any keypress

# Card selection mode:
# - "random": Randomly selects from active_cards list (default)
# - "sequential": Cycles through active_cards in order (not yet implemented)
# - "<card_name>": Always use a specific card (e.g., "matrix", "glitch", etc.)
card_selection = "random"

show_progress = true  # Show initialization progress bar

# All available splash cards are enabled by default for variety
# To customize: Remove cards you don't want, or replace the entire list with your preferred cards
# Static cards: default, classic, compact, minimal, blueprint
# Animated cards: matrix, glitch, retro, tech_pulse, code_scroll, minimal_fade, arcade_high_score,
#                digital_rain, loading_bar, starfield, terminal_boot, glitch_reveal, ascii_morph,
#                game_of_life, scrolling_credits, spotlight_reveal, sound_bars, raindrops_pond,
#                pixel_zoom, text_explosion, old_film, maze_generator, dwarf_fortress
active_cards = [
    "default", "matrix", "glitch", "retro", "classic", "compact", "minimal",
    "tech_pulse", "code_scroll", "minimal_fade", "blueprint", "arcade_high_score",
    "digital_rain", "loading_bar", "starfield", "terminal_boot", "glitch_reveal",
    "ascii_morph", "game_of_life", "scrolling_credits", "spotlight_reveal", "sound_bars",
    "raindrops_pond", "pixel_zoom", "text_explosion", "old_film", "maze_generator",
    "dwarf_fortress"
]

[splash_screen.effects]
# Animation effect settings
fade_in_duration = 0.3  # Fade in time in seconds
fade_out_duration = 0.2  # Fade out time in seconds
animation_speed = 1.0  # Animation playback speed multiplier

[api_settings]
# API endpoint configuration
# Each API provider can have its own configuration
# Format: [api_settings.<provider>]
#
# Refer to example configuration below and also to the default example config at:
# https://github.com/rmusser01/tldw/blob/dev/Config_Files/config.txt

[api_settings.openai]
api_key = ""
model = "gpt-4o-2024-11-20"
temperature = 0.7
max_tokens = 4096

# [api_settings.anthropic]
# api_key = ""
# model = "claude-3-5-sonnet-20241022"
# temperature = 0.7
# max_tokens = 4096

# --- Add other API providers as needed ---

[providers]
# List of available LLM providers to show in UI
available = ["openai", "anthropic", "local"]

[chat_defaults]
system_message = ""
provider = "openai"  # Default provider for new chats
model = ""  # Leave empty to use provider's default
temperature = 0.7
max_tokens = 4096
api_endpoint = ""

[character_defaults]
# Default settings for new character cards
version = "v3"
creator = ""
tags = []

[database]
# Database file paths (relative to user data directory)
prompts_db = "prompts.db"
rag_qa_db = "rag_qa.db"
character_chat_db = "chatDB.db"

[logging]
# Logging configuration
log_file = "chatbook.log"
file_log_level = "INFO"  # File logging level
console_log_level = "WARNING"  # Console/TUI logging level (for stderr)
log_format = "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{line} - {message}"
log_rotation = "10 MB"  # Rotate when file reaches this size
log_retention = "7 days"  # Keep logs for this duration
log_compression = "zip"  # Compress rotated logs

[notes]
# Notes feature settings
auto_save_enabled = true
auto_save_interval = 300  # seconds
sync_with_filesystem = true
default_template = ""

[themes]
# Custom theme definitions
# You can define your own themes here
# Example:
# [themes.my_custom_theme]
# primary = "#FF6B6B"
# secondary = "#4ECDC4"
# warning = "#FFE66D"
# error = "#FF6B6B"
# success = "#95E1D3"
# accent = "#C7CEEA"
# background = "#2D3436"
# surface = "#34495E"
# panel = "#2C3E50"
# dark = true

[encryption]
# Config file encryption settings (managed by the app)
enabled = false

# --- TTS Settings ---
[TTSSettings]
ALLTALK_TTS_URL_DEFAULT = "http://127.0.0.1:7851"
ALLTALK_TTS_VOICE_DEFAULT = "female_01.wav"
ALLTALK_TTS_LANGUAGE_DEFAULT = "en"
ALLTALK_TTS_OUTPUT_FORMAT_DEFAULT = "wav"

KOKORO_TTS_MODEL_DEFAULT = "kokoro-v0_19.onnx"
KOKORO_ONNX_MODELS_PATH_DEFAULT = "~/.config/tldw_cli/models/kokoro"
KOKORO_ONNX_VOICES_JSON_DEFAULT = "~/.config/tldw_cli/models/kokoro/voices.json"
KOKORO_DEVICE_DEFAULT = "cpu"  # Options: "cpu", "cuda", "cuda:0"
KOKORO_MAX_TOKENS = 500        # Maximum tokens per chunk
KOKORO_ENABLE_VOICE_MIXING = false  # Enable voice mixing feature
KOKORO_TRACK_PERFORMANCE = true     # Track performance metrics

# ElevenLabs TTS settings  
ELEVENLABS_API_KEY_fallback = ""  # Fallback if not in environment
ELEVENLABS_DEFAULT_VOICE = "21m00Tcm4TlvDq8ikWAM"  # Rachel voice ID
ELEVENLABS_DEFAULT_MODEL = "eleven_multilingual_v2"  # Options: eleven_multilingual_v2, eleven_turbo_v2
ELEVENLABS_OUTPUT_FORMAT = "mp3_44100_192"  # High quality MP3
ELEVENLABS_VOICE_STABILITY = 0.5    # Voice consistency (0.0-1.0)
ELEVENLABS_SIMILARITY_BOOST = 0.8   # Voice clarity (0.0-1.0)
ELEVENLABS_STYLE = 0.0              # Style exaggeration (0.0-1.0)
ELEVENLABS_USE_SPEAKER_BOOST = true # Enhanced speaker clarity

# --- STT Settings ---
[STTSettings]
# Default Speech-to-Text provider
# Options: "faster-whisper", "qwen2audio", "parakeet", "canary", "parakeet-mlx", "lightning-whisper-mlx"
# Note: On macOS, automatically defaults to parakeet-mlx or lightning-whisper-mlx if available
default_stt_provider = "faster-whisper"

# --- Search Settings ---
# [search_settings]
# default_provider = "google"
# ...