"""Legacy NewIngest compatibility exports."""

from .BackendIntegration import MediaProcessingService, ProcessingJobResult, get_processing_service
from .ProcessingDashboard import (
    JobStatusWidget,
    ProcessingCancelled,
    ProcessingDashboard,
    ProcessingJob,
    ProcessingJobStatus,
    ProcessingPaused,
    ProcessingResumed,
    ProcessingState,
)
from .SmartFileDropZone import FilePreviewItem, FileRemoved, FilesSelected, SmartFileDropZone
from .UnifiedProcessor import (
    AudioConfig,
    DocumentConfig,
    EbookConfig,
    MediaConfig,
    MediaSpecificOptions,
    ModeToggle,
    PDFConfig,
    ProcessingComplete,
    ProcessingError,
    ProcessingMode,
    ProcessingStarted,
    ProcessingStatus,
    UnifiedProcessor,
    VideoConfig,
    WebConfig,
)

__all__ = [
    "AudioConfig",
    "DocumentConfig",
    "EbookConfig",
    "FilePreviewItem",
    "FileRemoved",
    "FilesSelected",
    "JobStatusWidget",
    "MediaConfig",
    "MediaProcessingService",
    "MediaSpecificOptions",
    "ModeToggle",
    "PDFConfig",
    "ProcessingCancelled",
    "ProcessingComplete",
    "ProcessingDashboard",
    "ProcessingError",
    "ProcessingJob",
    "ProcessingJobResult",
    "ProcessingJobStatus",
    "ProcessingMode",
    "ProcessingPaused",
    "ProcessingResumed",
    "ProcessingStarted",
    "ProcessingState",
    "ProcessingStatus",
    "SmartFileDropZone",
    "UnifiedProcessor",
    "VideoConfig",
    "WebConfig",
    "get_processing_service",
]
