from pathlib import Path
import json, runpy
p=Path('tldw_chatbook/DB/recovery_core_schema.py'); text=p.read_text(); ns=runpy.run_path(str(p))
old=next(r[2] for r in ns['CORE_SCHEMAS'] if r[0]=='db.chachanotes.primary'); new=tuple(json.loads(Path('.superpowers/sdd/2026-10-03-console-chat-starts-dev-integration/catalogs.json').read_text())['core'])
changes=list(zip([s for s in old if s not in new],[s for s in new if s not in old])); assert len(changes)==2
for before,after in changes:assert ('console_dispatch_checkpoints' in before and 'console_dispatch_checkpoints' in after)
append='\n\n# ADR-211: exact constructor-captured v76 deltas; retain both qualified v75 catalogs.\nCHACHANOTES_V75_SCHEMA = next(row[2] for row in CORE_SCHEMAS if row[0] == "db.chachanotes.primary")\nCHACHANOTES_V75_DICTIONARY_UPDATE_SCHEMA = CHACHANOTES_DICTIONARY_UPDATE_SCHEMA\n_CHACHANOTES_V76_REPLACEMENTS = '+repr(dict(changes))+'\nCHACHANOTES_V76_SCHEMA = tuple(_CHACHANOTES_V76_REPLACEMENTS.get(sql, sql) for sql in CHACHANOTES_V75_SCHEMA)\nCORE_SCHEMAS = tuple((owner, 76, CHACHANOTES_V76_SCHEMA) if owner == "db.chachanotes.primary" else (owner, version, sql) for owner, version, sql in CORE_SCHEMAS)\nCHACHANOTES_DICTIONARY_UPDATE_SCHEMA = tuple(_CHACHANOTES_V76_REPLACEMENTS.get(sql, sql) for sql in CHACHANOTES_V75_DICTIONARY_UPDATE_SCHEMA)\n'
assert tuple(dict(changes).get(s,s) for s in old)==new
p.write_text(text+append)
p=Path('tldw_chatbook/DB/recovery_core.py');text=p.read_text().replace('            CHACHANOTES_DICTIONARY_UPDATE_SCHEMA,','            CHACHANOTES_DICTIONARY_UPDATE_SCHEMA,\n            CHACHANOTES_V75_SCHEMA,\n            CHACHANOTES_V75_DICTIONARY_UPDATE_SCHEMA,');text=text.replace('            schemas += ((version, CHACHANOTES_DICTIONARY_UPDATE_SCHEMA),)','            schemas += ((version, CHACHANOTES_DICTIONARY_UPDATE_SCHEMA), (75, CHACHANOTES_V75_SCHEMA), (75, CHACHANOTES_V75_DICTIONARY_UPDATE_SCHEMA))\n            versions += (75,)');p.write_text(text)
p=Path('Tests/Backup_Recovery/test_core_owners.py');text=p.read_text().replace('else (owner._CURRENT_SCHEMA_VERSION,)','else (owner._CURRENT_SCHEMA_VERSION, 75) if name == "chachanotes"\n        else (owner._CURRENT_SCHEMA_VERSION,)').replace('(2 if name in {"chachanotes", "prompts"} else 1)','(4 if name == "chachanotes" else 2 if name == "prompts" else 1)');p.write_text(text)
p=Path('Tests/Chat/test_console_chat_start.py');text=p.read_text().replace('    yield controller, source, db\n    controller.begin_shutdown()','    # Confirmation runs within the invoking primary worker context.\n    with use_run_id("source-run"):\n        yield controller, source, db\n    controller.begin_shutdown()');p.write_text(text)
print('Installed exactly two constructor-qualified core deltas; retained both v75 variants.')
