"""PR 0a contract: the support layer lives in Library_Modules; the screen re-exports it.

Written BEFORE the move (against the inventory generated by the brief's AST
script), so the move is proven by this test flipping from fail to pass, and
any future name deletion fails it.

See: .superpowers/sdd/2026-09-01-library-decomposition-foundation/task-1-brief.md
"""
from __future__ import annotations

import importlib

import pytest

# Name column of the inventory generated from `tldw_chatbook/UI/Screens/library_screen.py`
# (every module-level name above `class LibraryScreen`, minus `logger` which stays put),
# mapped to its destination module per the brief's file list.
#
# Three names from that inventory are deliberately EXCLUDED here and stay in
# `library_screen.py` unmoved: `_INGEST_OPTIONS_CACHE_ATTR`,
# `_read_library_ingest_options_from_config`, and `_library_ingest_options_for`.
# Several tests monkeypatch `get_cli_setting` / `_read_library_ingest_options_from_config`
# on the `library_screen` module, expecting the patch to reach
# `_library_ingest_options_for`'s internal call -- that only works while both
# functions share `library_screen.py`'s globals (a function's free-variable
# lookups resolve via `func.__globals__`, fixed at its *defining* module).
# Moving them breaks 5 tests deterministically (see
# `Library_Modules/screen_helpers.py`'s module docstring and this task's
# report for the full trace) -- the same "monkeypatch bypass breaks tests
# inside a pure move" risk the design doc names, with the same "stays
# screen-routed" mitigation it already uses for the `*_local_source_snapshot`
# trio.
_SURFACE = {
    "tldw_chatbook.UI.Library_Modules.screen_constants": [
        "LIBRARY_SKILLS_IMPORT_WORKER_GROUP",
        "LIBRARY_CONVERSATION_READER_PROFILE",
        "LIBRARY_COLLECTIONS_READER_PROFILE",
        "LIBRARY_NOTES_READER_PROFILE",
        "LIBRARY_FILE_NOTES_READER_PROFILE",
        "LIBRARY_PROMPTS_READER_PROFILE",
        "LIBRARY_SKILLS_READER_PROFILE",
        "LIBRARY_CONVERSATION_READER_MAX_CHARS",
        "LIBRARY_SOURCE_PAGE_SIZES",
        "LIBRARY_MEDIA_PREVIEW_CACHE_LIMIT",
        "_LIBRARY_PROMPTS_SEARCH_DEBOUNCE_SECONDS",
        "_LIBRARY_SKILLS_SORT_MODES",
        "_LIBRARY_PROMPT_IMPORT_PARSERS",
        "_LIBRARY_PROMPTS_IMPORT_WORKER_GROUP",
        "_LIBRARY_PROMPT_WRITE_WORKER_GROUPS",
        "_LIBRARY_PROMPT_WRITE_IN_PROGRESS_COPY",
        "LIBRARY_SERVICE_ERROR_COPY",
        "LIBRARY_SERVICE_UNAVAILABLE_COPY",
        "LIBRARY_EMPTY_COPY",
        "LIBRARY_SOURCE_SNAPSHOT_TIMEOUT_SECONDS",
        "LIBRARY_ONBOARDING_EVIDENCE_TIMEOUT_SECONDS",
        "LIBRARY_SNAPSHOT_CACHE_TTL_SECONDS",
        "LIBRARY_LIST_ENTRY_FOCUS_ARMED_SECONDS",
        "LIBRARY_NOTES_AUTOSAVE_SECONDS",
        "LIBRARY_NOTE_CONTENT_MAX_CHARS",
        "LIBRARY_NOTE_BLANK_SEED_TITLE",
        "LIBRARY_PROMPT_TEXT_MAX_CHARS",
        "LIBRARY_PROMPT_SAVE_STATUS_COPY",
        "LIBRARY_SKILL_TEXT_MAX_CHARS",
        "LIBRARY_PROMPT_DIRTY_VETO_COPY",
        "LIBRARY_SKILL_DIRTY_VETO_COPY",
        "LIBRARY_SKILL_TRUST_MISMATCH_COPY",
        "LIBRARY_SKILL_SAVE_STATUS_COPY",
        "LIBRARY_COLLECTION_SYNC_CONFLICT_LIMIT",
        "LIBRARY_HANDOFF_LABEL_PREFIX",
        "LIBRARY_WORKSPACE_SOURCE_COLUMN_WIDTH",
        "LIBRARY_WORKSPACE_SCOPE_COLUMN_WIDTH",
        "LIBRARY_WORKSPACE_VISIBLE_COLUMN_WIDTH",
        "LIBRARY_WORKSPACE_CONTEXT_COLUMN_WIDTH",
        "LIBRARY_HUB_RECENT_LABEL_WIDTH",
        "LIBRARY_MEDIA_HANDOFF_EXCERPT_CHARS",
        "LIBRARY_RAG_RESULTS_STATIC_WIDGET_IDS",
        "LIBRARY_NOTES_COMPACT_BREAKPOINT",
        "LIBRARY_INGEST_RAIL_COLLAPSE_BREAKPOINT",
        "_LIBRARY_READER_SHELL_SELECTOR",
        "LIBRARY_NOTES_SOURCE_DATABASE",
        "LIBRARY_NOTES_SOURCE_FILES",
        "LIBRARY_CANVAS_KIND_NOTES",
        "LIBRARY_NOTES_SOURCE_STRIP_CANVAS_KINDS",
        "LIBRARY_RAG_ANSWERABLE_RETRIEVAL_STATUSES",
        "LIBRARY_STUDY_HANDOFF_MODES",
        "LIBRARY_STUDY_HANDOFF_OWNERSHIP_COPY",
        "LIBRARY_STUDY_HANDOFF_TITLES_CAP",
        "LIBRARY_NAV_MODE_TO_ROW_ID",
        "LIBRARY_STUDY_HANDOFF_ROW_IDS",
        "_LIBRARY_LIST_ROW_CLASSES",
        "_LIBRARY_LIST_ROW_CLASS_BY_ROW_ID",
        "_LIBRARY_HELP_SURFACE_LABELS",
    ],
    "tldw_chatbook.UI.Library_Modules.screen_support_types": [
        "LibraryReaderDestination",
        "_LibraryIngestStartConsent",
        "LibraryEntryReconcileResult",
        "LibraryEntryFocusIdentity",
        "_LibraryEntryFocusCapture",
        "_LibraryMediaFinalFocusPolicy",
        "_LibraryMediaSettlementOutcome",
        "_LibraryMediaReturnReceipt",
        "_LibraryMediaReturnSettlement",
        "_LibraryMediaSuccessfulFocusOwnership",
        "_LibraryEmergencyReturnEligibility",
        "_LibraryEmergencyRestoreReceipt",
        "_LibraryNotesRecomposeCapture",
        "_LibraryNotesRestoreGuard",
        "_LibraryNotesDeletedFolderReceipt",
        "_ParakeetV2NoPendingReportError",
    ],
    "tldw_chatbook.UI.Library_Modules.note_session_port": [
        "_LibraryDatabaseNoteSessionPort",
    ],
    "tldw_chatbook.UI.Library_Modules.canvas_sync": [
        "_move_library_list_row_focus",
        "_patch_library_disabled_marker_label",
        "_apply_library_row_toggle",
        "_sync_library_canvas",
    ],
    "tldw_chatbook.UI.Library_Modules.screen_helpers": [
        "_library_screen_is_current",
        "library_note_persisted_title",
        "_ingestible_file_filters",
        "_transcribe_cpp_gguf_filters",
        "_library_carries_forward_line",
        "_unbreakable_size_text",
        "_active_library_sync_scope",
        "_record_value",
        "_library_collection_record_data",
        "_library_collection_browse_summary",
        "_collection_scoped_mirror_report",
        "_collection_scoped_conflicts",
        "_canonical_shortcut_key",
    ],
}


@pytest.mark.unit
@pytest.mark.parametrize("module,names", sorted(_SURFACE.items()))
def test_support_names_live_in_their_module(module: str, names: list[str]) -> None:
    mod = importlib.import_module(module)
    missing = [n for n in names if not hasattr(mod, n)]
    assert not missing, f"{module} missing {missing}"


@pytest.mark.unit
def test_screen_still_re_exports_every_moved_name() -> None:
    screen_mod = importlib.import_module("tldw_chatbook.UI.Screens.library_screen")
    for names in _SURFACE.values():
        missing = [n for n in names if not hasattr(screen_mod, n)]
        assert not missing, f"library_screen no longer re-exports {missing}"


#: Names deliberately EXCLUDED from the move (see the comment above _SURFACE):
#: they must stay DEFINED directly in library_screen.py, sharing its module
#: globals, not merely re-exported from a Library_Modules module -- that
#: distinction is exactly what keeps the ingest-options monkeypatch tests
#: passing. `__module__`/`__globals__` prove residency; `hasattr` alone would
#: pass just as happily for a re-export.
_INGEST_OPTIONS_TRIO_STAYS_ON_SCREEN = (
    "_INGEST_OPTIONS_CACHE_ATTR",
    "_read_library_ingest_options_from_config",
    "_library_ingest_options_for",
)


@pytest.mark.unit
def test_ingest_options_trio_is_not_moved_out_of_the_screen() -> None:
    """These 3 names must stay library_screen.py's OWN globals, not a re-export.

    Moving `_read_library_ingest_options_from_config` /
    `_library_ingest_options_for` out of `library_screen.py` gives their
    mutual internal call a different (unpatched) `__globals__`, silently
    bypassing the `get_cli_setting` / `_read_library_ingest_options_from_config`
    monkeypatches several tests apply to the `library_screen` module --
    breaking them without touching a single assertion. See the module
    docstring of `Library_Modules/screen_helpers.py`.
    """
    screen_mod = importlib.import_module("tldw_chatbook.UI.Screens.library_screen")
    for name in _INGEST_OPTIONS_TRIO_STAYS_ON_SCREEN:
        assert hasattr(screen_mod, name), f"library_screen lost {name!r}"
    for func_name in ("_read_library_ingest_options_from_config", "_library_ingest_options_for"):
        func = getattr(screen_mod, func_name)
        assert func.__globals__ is vars(screen_mod), (
            f"{func_name} no longer shares library_screen.py's module globals "
            "(it was moved to another module) -- this silently breaks the "
            "get_cli_setting monkeypatch tests rely on"
        )


@pytest.mark.unit
def test_no_import_cycle() -> None:
    import subprocess
    import sys

    for module in _SURFACE:
        proc = subprocess.run(
            [
                sys.executable,
                "-c",
                f"import sys, {module}; assert 'tldw_chatbook.UI.Screens.library_screen' not in sys.modules",
            ],
            capture_output=True,
            text=True,
        )
        assert proc.returncode == 0, f"{module} pulls in library_screen: {proc.stderr}"
