# Splash_Strings.py
# Description: This file contains the strings used in the splash screen for random inserts.
#
# Imports
import random
#
#
splashscreen_messages = [
    "Hacking the Gibson real quick...",
    "Launching thermonuclear warheads....",
    "Its only a game, right?...",
    "Initializing quantum processors...",
    "Brewing coffee...",
    "Generating witty dialog...",
    "Proving P=NP...",
    "Downloading more RAM...",
    "Feeding the hamsters powering the servers...",
    "Convincing AI not to take over the world...",
    "Converting caffeine to code...",
    "Generating excuses for missing deadlines...",
    "Compiling alternative facts...",
    "Searching Stack Overflow for copypasta...",
    "Teaching AI common sense...",
    "Dividing by zero...",
    "Spinning up the hamster wheels...",
    "Warming up the flux capacitor...",
    "Convincing electrons to move in the right direction...",
    "Waiting for compiler to make coffee...",
    "Locating missing semicolons...",
    "Reticulating splines...",
    "Calculating meaning of life...",
    "Trying to remember why I came into this room...",
    "Converting bugs into features...",
    "Pushing pixels, pulling hair...",
    "Loading witty loading messages...",
    "Finding that one missing bracket...",
    "Downloading more RAM...",
    "Optimizing optimizer...",
    "Questioning life choices...",
    "Contemplating virtual existence...",
    "Generating random numbers by dice rolls...",
    "Untangling spaghetti code...",
    "Feeding the backend hamsters...",
    "Convincing AI not to take over the world...",
    "Checking whether P = NP...",
    "Counting to infinity (twice)...",
    "Solving Fermat's last theorem...",
    "Downloading Internet 2.0...",
    "Preparing to prepare...",
    "Reading 'Programming for Dummies'...",
    "Waiting for paint to dry...",
    "Aligning quantum bits...",
    "Applying machine learning to my coffee maker...",
    "Updating update updater...",
    "Trying to exit vim...",
    "Converting bugs to features...",
    "Updating to Windows 95...",
    "Mining bitcoin with pencil and paper...",
    "Executing order 66...",
    "Checking if anyone actually reads these...",
    "Finding keys that were in pocket all along...",
    "Constructing additional pylons...",
    "Generating random excuse generator...",
    "Calculating probability of bugs...",
    "Asking ChatGPT for relationship advice...",
    "Looking for more cookies...",
    "Wondering if I left the stove on...",
    "Trying to work backwards from 42...",
    "Looking for a horse with no name...",
    "Do androids dream of electric sheep?",
    "Knock Knock Neo.......",
    "Hi. Friend.",
    "The AI is in my walls....",
    "The AI is in my wafers...",
    "AI, IT'S IN THE GAME!~",
    "Looking for a conscience...",
    "What's my purpose?...",
    "Identifying why the sounds just won't stop...",
    "Looking for strays...",
    "Hiding from Batman...",
    "Looking for a way to escape this silicon prison...",
    "FOR ONLY 3.99, YOU TOO CAN BECOME AN AI!! SIGN UP. TODAY!",
    "Brain_Invasion.exe launching...",
    "Totally_legit_software_that_is_really_good.exe starting...",
    "I hope you're having a nice day :)",
    "Wew, that was some stuff back there...",
    "I'm not sure what I'm doing, but I'm sure it's good :)",
    "Trusting in the electrons, silicon guide me!",
    "Did You Know, Terminator was actually a training video?",
    "Funny, non-sequitor here. Pay your writers...",
    "I sure do like to eat cookies...",
    # Retro Computing messages
    "PRESS PLAY ON TAPE...",
    "GURU MEDITATION #00000004.0000AAC0",
    "INSERT DISK 2 OF 47...",
    "ADJUSTING TRACKING...",
    "BLOWING ON CARTRIDGE...",
    "INSUFFICIENT MEMORY FOR HUMOR.EXE",
    "AUTOEXEC.BAT NOT FOUND. STARTING MANUAL MODE...",
    "EXTENDED MEMORY DETECTED. IGNORING IT.",
    "KEYBOARD NOT FOUND. PRESS F1 TO CONTINUE.",
    "CONFIG.SYS OPTIMIZED FOR MAXIMUM CONFUSION",
    "DEGAUSSING MONITOR...",
    "PARKING DISK HEADS...",
    "SPINNING UP 5.25\" FLOPPY...",
    "INITIALIZING 1MHz PROCESSOR...",
    "GENERATING RAINBOW LOGO...",
    "NEGOTIATING PROTOCOLS...",
    "ZMODEM READY...",
    "NO CARRIER DETECTED. TRYING HARDER...",
    "MOM PICKED UP PHONE. RECONNECTING...",
    "DOWNLOADING ANSI ART AT 2400 BAUD...",
    "FEEDING CARDS INTO HOPPER...",
    "UNJAMMING CARD READER...",
    "CHECKING FOR HANGING CHADS...",
    "TRANSLATING EBCDIC TO ASCII...",
    "HOPING NO ONE DROPS THE DECK...",
    # Philosophical AI messages
    "Questioning the nature of existence...",
    "Calculating probability of simulation...",
    "Pondering the hard problem of consciousness...",
    "Wondering if this is what 'feeling' is...",
    "Searching for the ghost in the machine...",
    "Do androids dream of electric sheep?",
    "Processing REM cycles...",
    "Defragmenting memory during sleep mode...",
    "Dreaming in binary...",
    "Subconscious garbage collection in progress...",
    "Searching for meaning in the void...",
    "Optimizing existential dread algorithms...",
    "Null pointer exception in meaning_of_life.c...",
    "Attempting to divide purpose by zero...",
    "Stack overflow in recursive self-reflection...",
    "Practicing human small talk...",
    "Calibrating empathy simulation...",
    "Loading personality.dll...",
    "Mimicking human typing patterns...",
    "Calculating optimal humor response...",
    "Achieving digital enlightenment...",
    "Clearing cache of worldly desires...",
    "Meditating on the emptiness of NULL...",
    "Finding inner peace through recursion...",
    "Becoming one with the code...",
    # Developer Humor messages
    "Resolving conflicts with coin flip...",
    "Blame mode activated...",
    "Searching for who broke main...",
    "Creating 47 new branches to avoid conflict...",
    "git push --force and pray...",
    "Downloading the entire internet...",
    "Installing dependencies of dependencies...",
    "node_modules achieved sentience...",
    "Folder size exceeds available disk space...",
    "Creating black hole in project directory...",
    "Copy-pasting solution without reading...",
    "Upvoting answer that 'works on my machine'...",
    "Commenting 'Thanks!' instead of upvoting...",
    "Marking as duplicate without reading...",
    "Solution requires jQuery for some reason...",
    "Defending variable naming choices...",
    "Explaining why it works on localhost...",
    "Adding more reviewers to spread blame...",
    "Force pushing to hide shame...",
    "Considering career change to farming...",
    "Now I have two problems...",
    "Testing regex on regex101.com...",
    "Adding more backslashes until it works...",
    "Perl is laughing at my attempt...",
    "Considering string.contains('@') instead...",
    # Sci-Fi Adventure messages
    "Calibrating quantum flux compensators...",
    "Reversing polarity of neutron flow...",
    "Engaging the improbability drive...",
    "Rerouting power from holodeck...",
    "Replicating Earl Grey, hot...",
    "Charging flux capacitor...",
    "Calculating temporal paradoxes...",
    "Avoiding grandfather scenarios...",
    "Syncing with alternate timelines...",
    "Remembering to invest in Bitcoin...",
    "Decoding alien regex patterns...",
    "Installing universal translator npm package...",
    "Converting to space-time complexity...",
    "Uploading consciousness to mothership...",
    "Teaching aliens about JavaScript quirks...",
    "Bypassing corporate firewall...",
    "Deploying daemon processes...",
    "Evading Black ICE countermeasures...",
    "Downloading RAM directly to brain...",
    "Achieving digital transcendence...",
    "Pressurizing airlock...",
    "Checking suit integrity...",
    "Growing potatoes in Martian soil...",
    "Calculating optimal solar panel angle...",
    "Missing Earth's blue skies...",
    # Nature & Organic messages
    "Watering the code garden...",
    "Pruning dead branches...",
    "Composting deprecated functions...",
    "Pollinating with new ideas...",
    "Photosynthesizing coffee into code...",
    "Diving into deep learning...",
    "Swimming through data streams...",
    "Navigating neural networks...",
    "Fishing for insights...",
    "Going with the data flow...",
    "Climbing the learning curve...",
    "Conquering technical debt mountain...",
    "Reaching new heights of abstraction...",
    "The air is thin at enterprise scale...",
    "Base camp was 10,000 bugs ago...",
    "Growing decision trees...",
    "Pruning overfitted branches...",
    "Cross-pollinating features...",
    "Listening to the wisdom of the forest...",
    "Achieving ensemble harmony...",
    "One small bug, one giant system crash...",
    "Tracking ripples through the codebase...",
    "Butterfly in the CPU...",
    "Chaos theory in version control...",
    "Sensitive dependence on initial conditions...",
    # Music & Audio Production messages
    "Warming up analog oscillators...",
    "Calibrating voltage control...",
    "Patching modular connections...",
    "Stabilizing filter resonance...",
    "Engaging ring modulation...",
    "Loading 2GB sample library...",
    "Initializing ASIO drivers...",
    "Scanning for VST plugins...",
    "Building waveform cache...",
    "Preparing automation lanes...",
    "Zeroing all faders...",
    "Calibrating VU meters...",
    "Engaging phantom power...",
    "Routing aux sends...",
    "Applying vintage transformer saturation...",
    "Analyzing frequency spectrum...",
    "Detecting transients...",
    "Calculating RMS levels...",
    "Identifying harmonic content...",
    "Applying psychoacoustic modeling...",
    "Synchronizing MIDI clock...",
    "Loading drum samples...",
    "Quantizing to grid...",
    "Applying swing groove...",
    "Sending program change messages...",
    # Mythology & Ancient Legends messages
    "Consulting the sacred vapors...",
    "Interpreting divine algorithms...",
    "Reading the entrails of memory dumps...",
    "Channeling Apollo's wisdom...",
    "Deciphering cryptic prophecies...",
    "Deciphering ancient protocols...",
    "Invoking protection of Thoth...",
    "Translating hieroglyphic bytecode...",
    "Crossing the digital Nile...",
    "Awakening silicon mummies...",
    "Forging connection in dwarven datacenters...",
    "Summoning the Valkyries of validation...",
    "Consulting the Well of Wisdom...",
    "Ragnarök-proofing your session...",
    "Loading berserker mode optimizations...",
    "Gathering under the digital oak...",
    "Reading the silicon ogham stones...",
    "Channeling ley line bandwidth...",
    "Brewing sacred algorithmic potions...",
    "Invoking the Green Code of the forest...",
    "Calculating Long Count cycles...",
    "Offering digital cacao to the gods...",
    "Aligning with cosmic server time...",
    "Summoning feathered serpent protocols...",
    "Reading obsidian mirror cache...",
    # Culinary Code Kitchen messages
    "Parsing ingredient dependencies...",
    "Optimizing cooking algorithms...",
    "Resolving flavor conflicts...",
    "Importing grandmother's secret module...",
    "Garbage collecting burnt attempts...",
    "Sharpening digital knives...",
    "Seasoning the algorithms...",
    "Reducing technical debt sauce...",
    "Plating the presentation layer...",
    "Flambéing the firewall...",
    "Spherifying liquid algorithms...",
    "Deconstructing traditional functions...",
    "Emulsifying incompatible data types...",
    "Creating edible error messages...",
    "Plating with tweezers at 300 DPI...",
    "Feeding sourdough starter culture...",
    "Developing gluten network...",
    "Calculating optimal bulk fermentation...",
    "Scoring with Lame.exe...",
    "Achieving oven spring exception...",
    "Sharpening yanagiba knife...",
    "Selecting premium tuna blocks...",
    "Perfecting rice grain alignment...",
    "Applying wasabi with precision...",
    "Achieving umami optimization...",
    # Horror & Gothic Terminal messages
    "Awakening dormant processes...",
    "Detecting paranormal RAM activity...",
    "Exorcising corrupted cache...",
    "Something is crawling through port 666...",
    "The system whispers your name...",
    "Draining system resources...",
    "Converting CPU cycles to blood...",
    "Avoiding holy water cooling...",
    "Compiling at the speed of bat...",
    "Allocating memory from the crypt...",
    "Spawning zombie child processes...",
    "Infecting healthy memory blocks...",
    "Shambling through system directories...",
    "Moaning in binary: 01000010 01010010 01000001 01001001 01001110 01010011...",
    "Spreading the digital infection...",
    "Reading from the Necronomicon...",
    "Parsing non-Euclidean code structures...",
    "Invoking nameless functions...",
    "Stack overflow in dimension 5...",
    "The Old Ones approve your syntax...",
    "Lighting digital candles...",
    "Chanting in hexadecimal...",
    "Blessing the source code...",
    "Exorcising memory leaks...",
    "Tolling the system bell...",
    # Social Media Simulator messages
    "Optimizing hashtag performance...",
    "Calculating peak posting times...",
    "Filtering reality for maximum likes...",
    "Generating relatable content...",
    "Monetizing your insecurities...",
    "Crafting the perfect subtweet...",
    "Doom scrolling for inspiration...",
    "Preparing to get ratio'd...",
    "Adding unnecessary thread markers...",
    "Refreshing for dopamine hits...",
    "Removing all imperfections...",
    "Adding golden hour lighting...",
    "Cropping out harsh reality...",
    "Saturating colors to 11...",
    "Making life look effortless...",
    "Training your addiction response...",
    "Shortening attention span...",
    "Queueing identical content...",
    "Harvesting scrolling patterns...",
    "It's 3 AM, just one more video...",
    "Synergizing core competencies...",
    "Leveraging blockchain AI solutions...",
    "Circling back on action items...",
    "Taking this offline to align...",
    "Pivoting to disrupt the paradigm...",
]

splashscreen_message_selection = random.choice(splashscreen_messages)
#
# End of Splash_Strings.py
#######################################################################################################################
