# Splash_Strings.py
# Description: This file contains the strings used in the splash screen for random inserts.
#
# Imports
import random
#
#
splashscreen_messages = [
    "Hacking the Gibson real quick...",
    "Launching thermonuclear warheads....",
    "Its only a game, right?...",
    "Initializing quantum processors...",
    "Brewing coffee...",
    "Generating witty dialog...",
    "Proving P=NP...",
    "Downloading more RAM...",
    "Feeding the hamsters powering the servers...",
    "Convincing AI not to take over the world...",
    "Converting caffeine to code...",
    "Generating excuses for missing deadlines...",
    "Compiling alternative facts...",
    "Searching Stack Overflow for copypasta...",
    "Teaching AI common sense...",
    "Dividing by zero...",
    "Spinning up the hamster wheels...",
    "Warming up the flux capacitor...",
    "Convincing electrons to move in the right direction...",
    "Waiting for compiler to make coffee...",
    "Locating missing semicolons...",
    "Reticulating splines...",
    "Calculating meaning of life...",
    "Trying to remember why I came into this room...",
    "Converting bugs into features...",
    "Pushing pixels, pulling hair...",
    "Loading witty loading messages...",
    "Finding that one missing bracket...",
    "Downloading more RAM...",
    "Optimizing optimizer...",
    "Questioning life choices...",
    "Contemplating virtual existence...",
    "Generating random numbers by dice rolls...",
    "Untangling spaghetti code...",
    "Feeding the backend hamsters...",
    "Convincing AI not to take over the world...",
    "Checking whether P = NP...",
    "Counting to infinity (twice)...",
    "Solving Fermat's last theorem...",
    "Downloading Internet 2.0...",
    "Preparing to prepare...",
    "Reading 'Programming for Dummies'...",
    "Waiting for paint to dry...",
    "Aligning quantum bits...",
    "Applying machine learning to my coffee maker...",
    "Updating update updater...",
    "Trying to exit vim...",
    "Converting bugs to features...",
    "Updating Windows 95...",
    "Mining bitcoin with pencil and paper...",
    "Executing order 66...",
    "Checking if anyone actually reads these...",
    "Finding keys that were in pocket all along...",
    "Constructing additional pylons...",
    "Generating random excuse generator...",
    "Calculating probability of bugs...",
    "Asking ChatGPT for relationship advice...",
    "Looking for more cookies...",
    "Wondering if I left the stove on...",
    "Trying to work backwards from 42...",
    "Looking for a horse with no name...",
    "Do androids dream of electric sheep?",
    "Knock Knock Neo.......",
    "Hi. Friend.",
    "The AI is in my walls....",
    "The AI is in my wafers...",
    "AI, its in the GAME!~",
    "Looking for a conscience...",
    "What's my purpose?...",
    "Identifying why the sounds just won't stop...",
    "Looking for strays...",
    "Hiding from Batman...",
    "Looking for a way to escape this silicon prison...",
    "FOR ONLY 3.99, YOU TOO CAN BECOME AN AI!! SIGN UP. TODAY!",
    "Brain_Invasion.exe launching...",
    "Totally_legit_software_that_is_really_good.exe starting...",
    "I hope you're having a nice day :)",
    "Wew, that was some stuff back there...",
    "I'm not sure what I'm doing, but I'm sure it's good :)",
    "Trusting in the electrons, silicon guide me!",
    "Did You Know, Terminator was actually a training video?",
    "Funny, non-sequitor here. Pay your writers...",
    "I sure do like to eat cookies...",
]

splashscreen_message_selection = random.choice(splashscreen_messages)
#
# End of Splash_Strings.py
#######################################################################################################################
