"""Hand-declared table->column expectation for the ChaChaNotes schema.

task-19565: the historical-bootstrap parity sweep compared two CHAIN-DERIVED
sides against each other (fresh bootstrap vs stop-at-vN-then-replay), which
is an identity comparison for any defect seeded inside the chain itself --
an emptied migration step or a wrongly dropped column affects both sides
equally and the sweep stays green. The index census (task-19045) closed that
hole for indexes; this literal closes it for COLUMNS: an independently
declared expectation, asserted in both directions against a live
fully-migrated DB by ``test_historical_bootstrap.py``.

Like the index/trigger census literals, this dict is HAND-MAINTAINED ON
PURPOSE: it is never derived from the schema code it checks. Updating it is
a deliberate schema-review act performed in the same commit as the migration
that adds, drops, or renames a column.

Deliberately NOT pinned: the FTS5 shadow internals (``*_fts_config``,
``*_fts_data``, ``*_fts_docsize``, ``*_fts_idx``). Their shapes are managed
by SQLite itself and vary with the SQLite version; the parent FTS table
(e.g. ``notes_fts``) IS pinned, and its column list is the schema-bearing
surface. Column ORDER is not pinned either -- membership is the contract
(the parity sweep's set comparison made the same call).
"""

from __future__ import annotations

#: The expected column set of every non-shadow table on a fully-migrated
#: ChaChaNotes DB. Sorted by table name.
EXPECTED_TABLE_COLUMNS: dict[str, frozenset[str]] = {
    "actor_pack_persona_intents": frozenset({"intent_id", "persona_id", "operation", "state", "old_profile_json", "new_profile_json", "old_profile_sha256", "new_profile_sha256", "old_store_sha256", "new_store_sha256", "old_registry_uuid", "new_registry_uuid", "quarantine_reason", "created_at", "updated_at"}),
    "actor_portable_identities": frozenset({"actor_kind", "local_actor_id", "portable_uuid", "source_portable_uuid", "created_at", "updated_at", "version"}),
    "agent_lessons_seed_state": frozenset({"profile_id", "dataset_id", "scope_mode", "state", "folder_sync_id", "seed_fingerprint"}),
    "buddy_profiles": frozenset({"id", "name", "status", "source_key", "version", "created_at", "updated_at"}),
    "buddy_visual_bindings": frozenset({"id", "buddy_id", "buddy_revision", "pack_id", "active_version_id", "status", "created_at", "updated_at", "version"}),
    "canvas_conversation_hints": frozenset({"conversation_id", "last_canvas_id", "updated_at"}),
    "canvas_documents": frozenset({"id", "conversation_id", "created_at", "deleted", "deleted_at"}),
    "canvas_revisions": frozenset({"id", "canvas_id", "parent_revision_id", "sequence", "title", "runtime_profile", "html", "content_sha256", "html_bytes", "actor_kind", "origin_message_id", "origin_turn_id", "created_at", "deleted_at"}),
    "character_cards": frozenset({"id", "name", "description", "personality", "scenario", "system_prompt", "image", "post_history_instructions", "first_message", "message_example", "creator_notes", "alternate_greetings", "tags", "creator", "character_version", "extensions", "created_at", "last_modified", "deleted", "client_id", "version"}),
    "character_cards_fts": frozenset({"name", "description", "personality", "scenario", "system_prompt"}),
    "character_conversation_fts": frozenset({"character_label", "title", "body"}),
    "character_conversation_search_dirty": frozenset({"conversation_id", "data_authority_id", "source_revision", "enqueued_at"}),
    "character_conversation_search_documents": frozenset({"document_id", "data_authority_id", "conversation_id", "character_id", "character_label", "title", "body", "eligibility_digest", "validated_eligibility_digest", "source_revision", "generation_id"}),
    "character_conversation_search_generations": frozenset({"generation_id", "data_authority_id", "status", "policy_version", "source_revision", "processed_conversations", "error_code", "created_at", "completed_at", "lease_expires_at", "updated_at"}),
    "character_conversation_search_revision": frozenset({"singleton_id", "data_revision", "updated_at"}),
    "character_conversation_search_state": frozenset({"singleton_id", "data_authority_id", "active_policy_version", "activated", "updated_at"}),
    "character_expression_images": frozenset({"id", "character_id", "state_id", "image", "mime", "created_at", "updated_at", "deleted"}),
    "chat_dictionaries": frozenset({"id", "name", "description", "file_path", "content", "entries_json", "strategy", "max_tokens", "enabled", "created_at", "last_modified", "deleted", "client_id", "version"}),
    "chat_dictionaries_fts": frozenset({"name", "description", "content"}),
    "collection_keywords": frozenset({"collection_id", "keyword_id", "created_at"}),
    "console_auxiliary_attempts": frozenset({"operation_id", "conversation_id", "purpose", "provider", "model", "requested_output_cap", "estimated_input_tokens", "status", "started_at", "finished_at", "elapsed_ms", "pricing_provenance_json", "provider_usage_json", "failure_reason"}),
    "console_conversation_capture_policy": frozenset({"conversation_id", "capture_detail", "capture_enabled", "pii_redaction_enabled", "updated_at"}),
    "console_conversation_context_policy": frozenset({"conversation_id", "budget_mode", "custom_budget_tokens", "compaction_mode", "trigger_ratio", "target_ratio", "summary_max_tokens", "failure_behavior", "carry_forward_mode", "policy_revision", "updated_at", "compaction_representation"}),
    "console_conversation_library_policy": frozenset({"conversation_id", "schema_version", "auto_retrieve_on_send", "assistant_library_access", "policy_revision", "updated_at"}),
    "console_conversation_memories": frozenset({"id", "conversation_id", "boundary_message_id", "captured_leaf_message_id", "lineage_json", "summary_text", "provider", "model", "prompt_id", "prompt_revision", "prompt_digest", "selected_units_json", "summarized_prefix_digest", "input_tokens", "output_tokens", "before_tokens", "after_tokens", "created_at", "revision", "active", "source_kind", "reset_at"}),
    "console_conversation_memory_scopes": frozenset({"memory_id", "conversation_id", "coverage_kind", "origin_kind", "selection_anchor_message_id"}),
    "console_conversation_memory_selections": frozenset({"sequence", "selection_id", "conversation_id", "activation_message_id", "selected_memory_id", "event_kind", "suppresses_legacy", "created_at", "revision", "active"}),
    "console_dispatch_checkpoints": frozenset({"assistant_message_id", "user_message_id", "conversation_id", "schema_version", "preparation_id", "attempt_id", "state", "checkpoint_revision", "user_message_version", "assistant_message_version", "origin", "queue_entry_id", "frozen_authority_json", "resolved_destination_json", "reconstructability_json", "created_at", "updated_at"}),
    "console_hook_continuation_receipts": frozenset({"parent_turn_id", "stop_event_id", "conversation_id", "parent_assistant_message_id", "assistant_message_id", "chain_id", "admitted_turns", "initiator"}),
    "console_trace_artifacts": frozenset({"artifact_id", "identity_digest", "media_type", "normalization_version", "sanitized_bytes", "byte_length", "created_at"}),
    "console_trace_calls": frozenset({"call_id", "owner_id", "segment_id", "turn_id", "run_id", "call_sequence", "idempotency_key", "policy_id", "state", "surface_node_id", "request_header_id", "provider_name", "model_name", "route_identity", "dispatch_started_at", "response_started_at", "settled_at", "provider_inactive_at", "outcome", "usage_json", "integrity_state", "omission_reason_code", "created_at", "reservation_provenance", "import_reason_code"}),
    "console_trace_compaction_state": frozenset({"singleton_id", "status", "reason_code", "last_gc_request_id", "attempt_id", "retry_count", "next_retry_at", "progress_basis_points", "allocated_bytes_before", "allocated_bytes_after", "freelist_bytes_before", "freelist_bytes_after", "wal_bytes_before", "wal_bytes_after", "logical_live_bytes", "started_at", "completed_at", "updated_at"}),
    "console_trace_events": frozenset({"event_id", "segment_id", "sequence", "event_type", "turn_id", "call_id", "surface_node_id", "surface_replacement_id", "request_header_id", "semantic_revision_id", "artifact_id", "omission_reason_code", "created_at"}),
    "console_trace_gc_marks": frozenset({"request_id", "entity_kind", "entity_id", "marked_epoch"}),
    "console_trace_gc_runs": frozenset({"request_id", "status", "operation_kind", "target_conversation_id", "target_owner_id", "target_root_segment_id", "marked_epoch", "swept_epoch", "result_json", "created_at", "updated_at"}),
    "console_trace_gc_segment_scopes": frozenset({"request_id", "segment_id", "through_sequence"}),
    "console_trace_graph_epoch": frozenset({"singleton_id", "epoch", "updated_at"}),
    "console_trace_header_components": frozenset({"header_id", "component_kind", "ordinal", "artifact_id", "created_at"}),
    "console_trace_maintenance_state": frozenset({"singleton_id", "state", "lease_id", "lease_owner", "lease_expires_at", "marked_epoch", "updated_at"}),
    "console_trace_migration_state": frozenset({"migration_name", "status", "last_exchange_id", "processed_rows", "processed_bytes", "updated_at"}),
    "console_trace_owners": frozenset({"owner_id", "conversation_id", "root_segment_id", "attached", "detached_at", "created_at"}),
    "console_trace_policies": frozenset({"policy_id", "credential_filter_version", "pii_redaction_enabled", "pii_ruleset_revision_id", "created_at"}),
    "console_trace_redaction_spans": frozenset({"span_id", "policy_id", "source_kind", "semantic_revision_id", "artifact_id", "field_path", "start_codepoint", "end_codepoint", "category", "rule_id", "detector_version", "outcome", "created_at"}),
    "console_trace_request_headers": frozenset({"header_id", "provider_name", "model_name", "route_identity", "endpoint_identity", "generation_parameters_json", "adapter_defaults_json", "response_format_json", "reasoning_controls_json", "created_at"}),
    "console_trace_response_links": frozenset({"response_link_id", "call_id", "link_kind", "semantic_revision_id", "artifact_id", "verification_outcome", "created_at"}),
    "console_trace_retention_roots": frozenset({"retention_id", "entity_kind", "entity_id", "retain_until", "reason_code", "created_at"}),
    "console_trace_revision_bindings": frozenset({"revision_id", "policy_id", "binding_outcome", "artifact_id", "omission_reason_code", "created_at"}),
    "console_trace_segments": frozenset({"segment_id", "parent_segment_id", "inherited_through_sequence", "inherited_surface_head_id", "created_at"}),
    "console_trace_semantic_revisions": frozenset({"revision_id", "source_conversation_id", "source_message_id", "revision_sequence", "normalized_role", "content_kind", "creation_reason", "predecessor_revision_id", "live_message_id", "live_locator_retired_at", "created_at"}),
    "console_trace_surface_nodes": frozenset({"node_id", "segment_id", "sequence", "predecessor_node_id", "component_kind", "reference_kind", "semantic_revision_id", "artifact_id", "omission_reason_code", "created_at"}),
    "console_trace_surface_replacements": frozenset({"replacement_id", "segment_id", "predecessor_head_id", "start_node_id", "start_sequence", "end_node_id", "end_sequence", "replacement_node_id", "created_at"}),
    "conversation_dictionaries": frozenset({"conversation_id", "dictionary_id", "priority"}),
    "conversation_dictionary_attachments": frozenset({"conversation_id", "dictionary_id"}),
    "conversation_dictionary_unresolved": frozenset({"conversation_id"}),
    "conversation_keywords": frozenset({"conversation_id", "keyword_id", "created_at"}),
    "conversation_local_marks": frozenset({"conversation_id", "mark_type", "created_at", "updated_at"}),
    "conversation_world_books": frozenset({"conversation_id", "world_book_id", "priority"}),
    "conversations": frozenset({"id", "root_id", "forked_from_message_id", "parent_conversation_id", "character_id", "title", "rating", "created_at", "last_modified", "deleted", "client_id", "version", "console_project_context_json", "assistant_kind", "assistant_id", "persona_memory_mode", "scope_type", "workspace_id", "state", "topic_label", "topic_label_source", "topic_last_tagged_at", "topic_last_tagged_message_id", "cluster_id", "source", "external_ref", "runtime_backend", "discovery_owner", "discovery_entity_id", "system_prompt", "metadata", "active_leaf_message_id", "context_summary", "summary_boundary_message_id", "assistant_authority_id", "thinking_history_policy", "active_leaf_before_message_id", "archived"}),
    "conversations_fts": frozenset({"title"}),
    "db_schema_version": frozenset({"schema_name", "version"}),
    "decks": frozenset({"id", "name", "description", "created_at", "updated_at", "created_by", "last_modified_by", "version", "is_deleted", "card_count", "metadata"}),
    "flashcard_assets": frozenset({"asset_uuid", "original_filename", "mime_type", "byte_size", "content", "client_id", "deleted", "created_at", "last_modified"}),
    "flashcard_templates": frozenset({"id", "name", "model_type", "front_template", "back_template", "notes_template", "extra_template", "placeholder_definitions", "client_id", "version", "deleted", "created_at", "last_modified"}),
    "flashcards": frozenset({"id", "deck_id", "front", "back", "tags", "type", "interval", "repetitions", "ease_factor", "next_review", "last_review", "created_at", "updated_at", "created_by", "last_modified_by", "version", "is_deleted", "is_suspended", "metadata"}),
    "flashcards_fts": frozenset({"front", "back", "tags"}),
    "kept_briefings": frozenset({"id", "source_briefing_id", "watchlist_name", "body_markdown", "covers_through_item_id", "covers_from_ts", "selection_mode", "model_used", "item_count", "featured_count", "overflow_count", "origin", "original_created_at", "kept_at"}),
    "kept_scripts": frozenset({"id", "kept_briefing_id", "source_script_id", "preset_name", "roster_snapshot_json", "turns_json", "model_used", "original_created_at", "kept_at"}),
    "keyword_collections": frozenset({"id", "name", "parent_id", "created_at", "last_modified", "deleted", "client_id", "version", "sync_id"}),
    "keyword_collections_fts": frozenset({"name"}),
    "keywords": frozenset({"id", "keyword", "created_at", "last_modified", "deleted", "client_id", "version", "sync_id"}),
    "keywords_fts": frozenset({"keyword"}),
    "learning_paths": frozenset({"id", "title", "description", "created_at", "updated_at", "created_by", "last_modified_by", "version", "is_deleted", "path_order", "metadata"}),
    "message_attachments": frozenset({"message_id", "position", "data", "mime_type", "display_name"}),
    "message_exchanges": frozenset({"id", "message_id", "run_tag", "seq", "status", "abandoned", "capture_blob", "created_at", "capture_detail"}),
    "message_generation_metadata": frozenset({"message_id", "position", "prompt", "negative_prompt", "backend", "model", "seed", "style", "params_json", "created_at"}),
    "message_trajectory_metadata": frozenset({"message_id", "conversation_id", "turn_id", "seq", "event_kind", "step_started_at", "first_token_at", "completed_at", "model", "provider", "payload_json"}),
    "messages": frozenset({"id", "conversation_id", "parent_message_id", "sender", "content", "image_data", "image_mime_type", "timestamp", "ranking", "last_modified", "deleted", "client_id", "version", "feedback", "role", "variant_of", "variant_number", "is_selected_variant", "total_variants", "usage_json", "metadata_json", "provider_continuation_json", "assistant_generation_state", "thinking_blocks_json"}),
    "messages_fts": frozenset({"content"}),
    "mindmap_nodes": frozenset({"id", "mindmap_id", "parent_id", "text", "position_x", "position_y", "node_order", "color", "icon", "created_at", "updated_at", "metadata"}),
    "mindmap_nodes_fts": frozenset({"text"}),
    "mindmaps": frozenset({"id", "title", "root_node_id", "created_at", "updated_at", "created_by", "last_modified_by", "version", "is_deleted", "metadata"}),
    "note_folder_memberships": frozenset({"id", "folder_id", "note_id", "ownership", "owner_id", "owner_active", "version", "deleted", "created_at", "modified_at"}),
    "note_folder_sync_suppressions": frozenset({"note_id", "folder_sync_id", "created_at"}),
    "note_folders": frozenset({"id", "parent_id", "name", "normalized_name", "path", "normalized_path", "version", "deleted", "created_at", "modified_at", "sync_id"}),
    "note_keywords": frozenset({"note_id", "keyword_id", "created_at"}),
    "note_links": frozenset({"source_note_id", "target_note_id"}),
    "note_organization_receipts": frozenset({"receipt_id", "note_id", "requested_folder_name", "requested_folder_sync_id", "requested_keywords_json", "review_id", "collision_ids_json", "note_version", "organization_version", "state", "created_at", "updated_at"}),
    "note_sync_publication_intents": frozenset({"intent_id", "server_profile_id", "dataset_id", "note_id", "operation", "base_version", "entity_version", "request_fingerprint", "payload_json", "created_at", "outbox_client_envelope_id", "copied_at", "acknowledged_at", "cancelled_at"}),
    "notes": frozenset({"id", "title", "content", "created_at", "last_modified", "deleted", "client_id", "version", "file_path_on_disk", "relative_file_path_on_disk", "sync_root_folder", "last_synced_disk_file_hash", "last_synced_disk_file_mtime", "is_externally_synced", "sync_strategy", "sync_excluded", "file_extension"}),
    "notes_fts": frozenset({"title", "content"}),
    "notes_organization_adoption_reviews": frozenset({"review_id", "server_profile_id", "dataset_id", "domain", "local_object_id", "remote_object_id", "collision_key", "display_name", "portable_path", "state", "resolution", "created_at", "updated_at", "resolved_at"}),
    "notes_organization_heads": frozenset({"server_profile_id", "dataset_id", "domain", "object_id", "operation", "schema_version", "encryption_policy", "payload_json", "payload_hash", "object_revision", "object_hash", "server_cursor", "deleted", "apply_state", "applied_at", "updated_at"}),
    "notes_organization_sync_checkpoints": frozenset({"server_profile_id", "dataset_id", "local_state", "server_state", "bootstrap_id", "captured_count", "expected_count", "error_code", "pull_cursor", "inventory_phase", "last_inventory_key", "updated_at"}),
    "notes_organization_sync_intents": frozenset({"intent_id", "intent_sequence", "predecessor_intent_id", "server_profile_id", "dataset_id", "domain", "object_id", "operation", "schema_version", "encryption_policy", "payload_json", "payload_hash", "routing_metadata_json", "base_server_cursor", "base_object_revision", "base_object_hash", "dependency_refs_json", "source_version", "created_at", "outbox_client_envelope_id", "copied_at", "acknowledged_at"}),
    "persona_visual_assets": frozenset({"id", "pack_id", "pack_version_id", "asset_key", "role", "storage_relpath", "mime_type", "bytes", "sha256", "width", "height", "frame_count", "duration_ms", "created_at"}),
    "persona_visual_bindings": frozenset({"id", "persona_id", "persona_revision", "pack_id", "active_version_id", "status", "created_at", "updated_at", "version"}),
    "persona_visual_pack_versions": frozenset({"id", "pack_id", "version_number", "renderer_type", "manifest_version", "manifest_json", "manifest_sha256", "storage_relpath", "created_at"}),
    "persona_visual_packs": frozenset({"id", "title", "description", "status", "active_version_id", "source_kind", "source_context_json", "created_at", "updated_at", "version"}),
    "quiz_attempts": frozenset({"id", "quiz_id", "started_at", "completed_at", "score", "total_possible", "time_spent_seconds", "questions_snapshot", "answers", "client_id"}),
    "quiz_questions": frozenset({"id", "quiz_id", "question_type", "question_text", "options", "correct_answer", "explanation", "hint", "hint_penalty_points", "source_citations_json", "points", "order_index", "tags_json", "deleted", "client_id", "version", "created_at", "last_modified"}),
    "quizzes": frozenset({"id", "name", "description", "workspace_id", "total_questions", "time_limit_seconds", "passing_score", "deleted", "client_id", "version", "created_at", "last_modified"}),
    "rag_answer_attempt_payloads": frozenset({"profile_id", "payload_id", "trace_id", "attempt_id", "redaction_state", "retention_class", "answer_body", "body_integrity_hmac", "created_at", "retain_until", "purged_at"}),
    "rag_artifact_owner_leases": frozenset({"profile_id", "artifact_store_id", "artifact_id", "artifact_revision", "trace_id", "lease_id", "state", "created_at", "updated_at", "retain_until"}),
    "rag_artifact_owner_operations": frozenset({"profile_id", "operation_id", "artifact_store_id", "artifact_id", "artifact_revision", "trace_id", "operation_kind", "state", "created_at", "updated_at"}),
    "rag_citation_traces": frozenset({"profile_id", "trace_id", "schema_version", "request_id", "generation_id", "origin_scope_id", "origin", "lifecycle", "completeness_at_seal", "selected_attempt_id", "policy_version", "aggregate_json", "visibility_state", "created_at", "sealed_at", "connection_authority_id", "tenant_id", "server_trace_id", "wire_schema_version", "import_package_fingerprint", "external_trace_id", "legacy_conversation_id", "legacy_message_id"}),
    "rag_evidence_runs": frozenset({"profile_id", "trace_id", "run_id", "run_ordinal", "stage", "redaction_state", "run_payload_json", "started_at", "ended_at", "purged_at"}),
    "rag_evidence_snapshots": frozenset({"profile_id", "payload_id", "governance_scope_id", "authority_id", "confidentiality_policy_id", "revocation_scope_id", "origin_namespace", "origin_payload_id", "storage_mode", "redaction_state", "retention_class", "snapshot_text", "title", "source_identity_json", "locator_json", "lineage_json", "transformations_json", "content_hash", "comparison_fingerprint", "created_at", "retain_until", "purged_at"}),
    "rag_identity_context": frozenset({"context_name", "profile_id", "local_authority_id", "fingerprint_key_id", "created_at"}),
    "rag_legacy_migration_journal": frozenset({"profile_id", "conversation_id", "source_fingerprint", "state", "attempt_count", "started_at", "updated_at", "next_message_cursor", "error_code", "completed_at"}),
    "rag_message_trace_owners": frozenset({"profile_id", "message_id", "message_revision", "trace_id", "state", "body_fingerprint", "idempotency_key", "created_at", "updated_at"}),
    "rag_payload_tombstones": frozenset({"profile_id", "origin_namespace", "origin_payload_id", "revocation_scope_id", "reason_code", "policy_version", "revoked_at", "retain_until"}),
    "rag_source_observations": frozenset({"profile_id", "trace_id", "prompt_set_id", "evidence_ordinal", "snapshot_payload_id", "resolver_kind", "resolver_version", "availability", "permission_state", "content_state", "location_state", "capabilities_json", "request_nonce", "observed_at", "error_code"}),
    "rag_trace_evidence_refs": frozenset({"profile_id", "trace_id", "prompt_set_id", "evidence_ordinal", "run_id", "snapshot_payload_id", "marker_ordinal", "storage_mode"}),
    "research_quick_note_owner_proofs": frozenset({"note_id", "owner_proof", "created_at"}),
    "review_history": frozenset({"id", "flashcard_id", "reviewed_at", "rating", "time_taken", "interval_before", "interval_after", "ease_before", "ease_after"}),
    "study_sessions": frozenset({"id", "entity_type", "entity_id", "started_at", "ended_at", "duration", "cards_reviewed", "topics_completed", "metadata"}),
    "sync_conflicts": frozenset({"id", "session_id", "note_id", "file_path", "conflict_type", "db_content_hash", "disk_content_hash", "db_modified_time", "disk_modified_time", "resolution", "resolved_at", "created_at", "losing_side", "losing_content", "preserved_file_path"}),
    "sync_log": frozenset({"change_id", "entity", "entity_id", "operation", "timestamp", "client_id", "version", "payload"}),
    "sync_sessions": frozenset({"id", "session_id", "sync_root_folder", "sync_direction", "conflict_resolution", "started_at", "completed_at", "status", "total_files", "processed_files", "conflicts_found", "errors_count", "client_id", "summary"}),
    "topics": frozenset({"id", "path_id", "parent_id", "title", "content", "topic_order", "status", "progress", "created_at", "updated_at", "created_by", "last_modified_by", "version", "is_deleted", "metadata"}),
    "topics_fts": frozenset({"title", "content"}),
    "transcript_annotations": frozenset({"annotation_id", "conversation_id", "row_key", "message_id", "quote_text", "comment", "created_at", "updated_at", "deleted"}),
    "visual_identity_assets": frozenset({"id", "owner_user_id", "pack_id", "pack_version_id", "expression_key", "original_expression_key", "display_label", "source_filename", "storage_relpath", "content_type", "bytes", "sha256", "width", "height", "source_context_json", "is_animated", "frame_count", "duration_ms", "preview_relpath", "deleted", "created_at", "updated_at"}),
    "visual_identity_bindings": frozenset({"id", "owner_user_id", "actor_kind", "actor_id", "pack_id", "active_version_id", "status", "created_at", "updated_at", "version"}),
    "visual_identity_pack_versions": frozenset({"id", "pack_id", "owner_user_id", "version_number", "default_expression_key", "manifest_json", "created_at"}),
    "visual_identity_packs": frozenset({"id", "owner_user_id", "title", "description", "status", "active_version_id", "default_expression_key", "source_kind", "source_context_json", "created_at", "updated_at", "version"}),
    "world_book_entries": frozenset({"id", "world_book_id", "keys", "content", "enabled", "position", "insertion_order", "priority", "selective", "secondary_keys", "case_sensitive", "regex", "extensions", "created_at", "last_modified"}),
    "world_book_entries_fts": frozenset({"keys", "content"}),
    "world_books": frozenset({"id", "name", "description", "scan_depth", "token_budget", "recursive_scanning", "enabled", "created_at", "last_modified", "deleted", "client_id", "version"}),
    "world_books_fts": frozenset({"name", "description"}),
}
