"""Compatibility-preserving lazy public exports; recovery imports no services."""

from importlib import import_module

_EXPORTS = {
    'CONSOLE_CONVERSATION_BROWSER_GROUP_ROW_LIMIT': ('.conversation_browser_state', 'CONSOLE_CONVERSATION_BROWSER_GROUP_ROW_LIMIT'),
    'CONSOLE_CONVERSATION_BROWSER_RESULT_LIMIT': ('.conversation_browser_state', 'CONSOLE_CONVERSATION_BROWSER_RESULT_LIMIT'),
    'ConsoleConversationBrowserGroup': ('.conversation_browser_state', 'ConsoleConversationBrowserGroup'),
    'ConsoleConversationBrowserInputRow': ('.conversation_browser_state', 'ConsoleConversationBrowserInputRow'),
    'ConsoleConversationBrowserRow': ('.conversation_browser_state', 'ConsoleConversationBrowserRow'),
    'ConsoleConversationBrowserSection': ('.conversation_browser_state', 'ConsoleConversationBrowserSection'),
    'ConsoleConversationBrowserState': ('.conversation_browser_state', 'ConsoleConversationBrowserState'),
    'build_console_conversation_browser_state': ('.conversation_browser_state', 'build_console_conversation_browser_state'),
    'console_persisted_row_updated_sort': ('.conversation_browser_state', 'console_persisted_row_updated_sort'),
    'CONSOLE_WORKSPACE_CONVERSATION_RESULT_LIMIT': ('.display_state', 'CONSOLE_WORKSPACE_CONVERSATION_RESULT_LIMIT'),
    'ConsoleWorkspaceACPHandoffState': ('.display_state', 'ConsoleWorkspaceACPHandoffState'),
    'ConsoleWorkspaceContextState': ('.display_state', 'ConsoleWorkspaceContextState'),
    'ConsoleWorkspaceConversationRow': ('.display_state', 'ConsoleWorkspaceConversationRow'),
    'ConsoleWorkspaceConversationSectionState': ('.display_state', 'ConsoleWorkspaceConversationSectionState'),
    'ConsoleWorkspaceHandoffRow': ('.display_state', 'ConsoleWorkspaceHandoffRow'),
    'ConsoleWorkspaceServerAdapterState': ('.display_state', 'ConsoleWorkspaceServerAdapterState'),
    'LibraryWorkspaceDepthState': ('.display_state', 'LibraryWorkspaceDepthState'),
    'LibraryWorkspaceSourceRow': ('.display_state', 'LibraryWorkspaceSourceRow'),
    'build_library_workspace_depth_state': ('.display_state', 'build_library_workspace_depth_state'),
    'library_item_context_handoff': ('.display_state', 'library_item_context_handoff'),
    'build_console_workspace_state': ('.display_state', 'build_console_workspace_state'),
    'console_workspace_conversation_result_copy': ('.display_state', 'console_workspace_conversation_result_copy'),
    'console_workspace_conversation_visible_rows': ('.display_state', 'console_workspace_conversation_visible_rows'),
    'evaluate_workspace_eligibility': ('.eligibility', 'evaluate_workspace_eligibility'),
    'DEFAULT_WORKSPACE_ID': ('.models', 'DEFAULT_WORKSPACE_ID'),
    'DEFAULT_WORKSPACE_NAME': ('.models', 'DEFAULT_WORKSPACE_NAME'),
    'RuntimeBindingKind': ('.models', 'RuntimeBindingKind'),
    'RuntimeBindingStatus': ('.models', 'RuntimeBindingStatus'),
    'WorkspaceAuthority': ('.models', 'WorkspaceAuthority'),
    'WorkspaceEligibility': ('.models', 'WorkspaceEligibility'),
    'WorkspaceMembership': ('.models', 'WorkspaceMembership'),
    'WorkspaceOperation': ('.models', 'WorkspaceOperation'),
    'WorkspaceRecord': ('.models', 'WorkspaceRecord'),
    'WorkspaceRuntimeBinding': ('.models', 'WorkspaceRuntimeBinding'),
    'WorkspaceSyncStatus': ('.models', 'WorkspaceSyncStatus'),
    'WorkspaceTransferPolicy': ('.models', 'WorkspaceTransferPolicy'),
    'BindingNotFound': ('.registry_service', 'BindingNotFound'),
    'LocalWorkspaceRegistryService': ('.registry_service', 'LocalWorkspaceRegistryService'),
    'CONSOLE_CONVERSATION_BROWSER_ROW_HEIGHT': ('.conversation_browser_state', 'CONSOLE_CONVERSATION_BROWSER_ROW_HEIGHT'),
    'CONSOLE_RAIL_SECTION_MIN_BUDGET_LINES': ('.conversation_browser_state', 'CONSOLE_RAIL_SECTION_MIN_BUDGET_LINES'),
    'console_conversation_browser_group_row_limit': ('.conversation_browser_state', 'console_conversation_browser_group_row_limit'),
    'console_conversation_starred_recency_sort_key': ('.conversation_browser_state', 'console_conversation_starred_recency_sort_key'),
    'console_rail_section_height_budget': ('.conversation_browser_state', 'console_rail_section_height_budget'),
    'overlay_console_conversation_markers': ('.conversation_browser_state', 'overlay_console_conversation_markers'),
    'ChangeReviewAdmission': ('.change_review_consent', 'ChangeReviewAdmission'),
    'ChangeReviewCapability': ('.change_review_consent', 'ChangeReviewCapability'),
    'ChangeReviewConsent': ('.change_review_consent', 'ChangeReviewConsent'),
    'ChangeReviewConsentService': ('.change_review_consent', 'ChangeReviewConsentService'),
    'ChangeReviewState': ('.change_review_consent', 'ChangeReviewState'),
    'ChangeReviewStateConflict': ('.change_review_consent', 'ChangeReviewStateConflict'),
    'ChangeReviewStatus': ('.change_review_consent', 'ChangeReviewStatus'),
    'RootReadiness': ('.change_review_consent', 'RootReadiness'),
    'RootReadinessState': ('.change_review_consent', 'RootReadinessState'),
    'SkippedReviewRoot': ('.change_review_consent', 'SkippedReviewRoot'),
    'ChangeReviewFinalizeResult': ('.change_review_finalization', 'ChangeReviewFinalizeResult'),
    'ChangeReviewFinalizationCoordinator': ('.change_review_finalization', 'ChangeReviewFinalizationCoordinator'),
    'ChangeReviewPublication': ('.change_review_finalization', 'ChangeReviewPublication'),
    'ChangeReviewPublicationSignal': ('.change_review_finalization', 'ChangeReviewPublicationSignal'),
    'ChangeReviewPublicationSnapshot': ('.change_review_finalization', 'ChangeReviewPublicationSnapshot'),
    'ChangeReviewReservation': ('.change_review_finalization', 'ChangeReviewReservation'),
    'ResearchQuickNoteReceipt': ('.models', 'ResearchQuickNoteReceipt'),
    'DeferredWorkspaceToolProfileGuard': ('.registry_service', 'DeferredWorkspaceToolProfileGuard'),
    'WorkspaceTreeConversation': ('.workspace_tree_state', 'WorkspaceTreeConversation'),
    'WorkspaceTreeWorkspace': ('.workspace_tree_state', 'WorkspaceTreeWorkspace'),
    'build_workspace_tree_state': ('.workspace_tree_state', 'build_workspace_tree_state'),
    'update_workspace_tree_conversation': ('.workspace_tree_state', 'update_workspace_tree_conversation'),
}

__all__ = [
    "CONSOLE_CONVERSATION_BROWSER_GROUP_ROW_LIMIT",
    "CONSOLE_CONVERSATION_BROWSER_RESULT_LIMIT",
    "CONSOLE_CONVERSATION_BROWSER_ROW_HEIGHT",
    "CONSOLE_RAIL_SECTION_MIN_BUDGET_LINES",
    "CONSOLE_WORKSPACE_CONVERSATION_RESULT_LIMIT",
    "BindingNotFound",
    "DeferredWorkspaceToolProfileGuard",
    "ChangeReviewAdmission",
    "ChangeReviewCapability",
    "ChangeReviewConsent",
    "ChangeReviewConsentService",
    "ChangeReviewFinalizeResult",
    "ChangeReviewFinalizationCoordinator",
    "ChangeReviewPublication",
    "ChangeReviewPublicationSignal",
    "ChangeReviewPublicationSnapshot",
    "ChangeReviewReservation",
    "ChangeReviewState",
    "ChangeReviewStateConflict",
    "ChangeReviewStatus",
    "ConsoleConversationBrowserGroup",
    "ConsoleConversationBrowserInputRow",
    "ConsoleConversationBrowserRow",
    "ConsoleConversationBrowserSection",
    "ConsoleConversationBrowserState",
    "ConsoleWorkspaceContextState",
    "ConsoleWorkspaceConversationRow",
    "ConsoleWorkspaceConversationSectionState",
    "ConsoleWorkspaceACPHandoffState",
    "ConsoleWorkspaceHandoffRow",
    "ConsoleWorkspaceServerAdapterState",
    "DEFAULT_WORKSPACE_ID",
    "DEFAULT_WORKSPACE_NAME",
    "LibraryWorkspaceDepthState",
    "LibraryWorkspaceSourceRow",
    "LocalWorkspaceRegistryService",
    "RuntimeBindingKind",
    "RuntimeBindingStatus",
    "RootReadiness",
    "RootReadinessState",
    "SkippedReviewRoot",
    "ResearchQuickNoteReceipt",
    "WorkspaceAuthority",
    "WorkspaceEligibility",
    "WorkspaceMembership",
    "WorkspaceOperation",
    "WorkspaceRecord",
    "WorkspaceRuntimeBinding",
    "WorkspaceSyncStatus",
    "WorkspaceTransferPolicy",
    "WorkspaceTreeConversation",
    "WorkspaceTreeWorkspace",
    "build_console_conversation_browser_state",
    "build_workspace_tree_state",
    "build_library_workspace_depth_state",
    "library_item_context_handoff",
    "build_console_workspace_state",
    "console_conversation_browser_group_row_limit",
    "console_persisted_row_updated_sort",
    "console_rail_section_height_budget",
    "console_conversation_starred_recency_sort_key",
    "overlay_console_conversation_markers",
    "console_workspace_conversation_result_copy",
    "console_workspace_conversation_visible_rows",
    "evaluate_workspace_eligibility",
    "update_workspace_tree_conversation",
]


def __getattr__(name):
    if name not in _EXPORTS:
        raise AttributeError(name)
    module, symbol = _EXPORTS[name]
    value = getattr(import_module(module, __name__), symbol)
    globals()[name] = value
    return value
