"""Workspace operating-context APIs."""

from .conversation_browser_state import (
    CONSOLE_CONVERSATION_BROWSER_GROUP_ROW_LIMIT,
    CONSOLE_CONVERSATION_BROWSER_RESULT_LIMIT,
    ConsoleConversationBrowserGroup,
    ConsoleConversationBrowserInputRow,
    ConsoleConversationBrowserRow,
    ConsoleConversationBrowserSection,
    ConsoleConversationBrowserState,
    build_console_conversation_browser_state,
    console_conversation_starred_recency_sort_key,
    console_persisted_row_updated_sort,
    overlay_console_conversation_markers,
)
from .display_state import (
    CONSOLE_WORKSPACE_CONVERSATION_RESULT_LIMIT,
    ConsoleWorkspaceACPHandoffState,
    ConsoleWorkspaceContextState,
    ConsoleWorkspaceConversationRow,
    ConsoleWorkspaceConversationSectionState,
    ConsoleWorkspaceHandoffRow,
    ConsoleWorkspaceServerAdapterState,
    LibraryWorkspaceDepthState,
    LibraryWorkspaceSourceRow,
    build_library_workspace_depth_state,
    library_item_context_handoff,
    build_console_workspace_state,
    console_workspace_conversation_result_copy,
    console_workspace_conversation_visible_rows,
)
from .eligibility import evaluate_workspace_eligibility
from .models import (
    DEFAULT_WORKSPACE_ID,
    DEFAULT_WORKSPACE_NAME,
    RuntimeBindingKind,
    RuntimeBindingStatus,
    WorkspaceAuthority,
    WorkspaceEligibility,
    WorkspaceMembership,
    WorkspaceOperation,
    WorkspaceRecord,
    WorkspaceRuntimeBinding,
    WorkspaceSyncStatus,
    WorkspaceTransferPolicy,
)
from .registry_service import BindingNotFound, LocalWorkspaceRegistryService
from .workspace_tree_state import (
    WorkspaceTreeConversation,
    WorkspaceTreeWorkspace,
    build_workspace_tree_state,
    update_workspace_tree_conversation,
)

__all__ = [
    "CONSOLE_CONVERSATION_BROWSER_GROUP_ROW_LIMIT",
    "CONSOLE_CONVERSATION_BROWSER_RESULT_LIMIT",
    "CONSOLE_WORKSPACE_CONVERSATION_RESULT_LIMIT",
    "BindingNotFound",
    "ConsoleConversationBrowserGroup",
    "ConsoleConversationBrowserInputRow",
    "ConsoleConversationBrowserRow",
    "ConsoleConversationBrowserSection",
    "ConsoleConversationBrowserState",
    "ConsoleWorkspaceContextState",
    "ConsoleWorkspaceConversationRow",
    "ConsoleWorkspaceConversationSectionState",
    "ConsoleWorkspaceACPHandoffState",
    "ConsoleWorkspaceHandoffRow",
    "ConsoleWorkspaceServerAdapterState",
    "DEFAULT_WORKSPACE_ID",
    "DEFAULT_WORKSPACE_NAME",
    "LibraryWorkspaceDepthState",
    "LibraryWorkspaceSourceRow",
    "LocalWorkspaceRegistryService",
    "RuntimeBindingKind",
    "RuntimeBindingStatus",
    "WorkspaceAuthority",
    "WorkspaceEligibility",
    "WorkspaceMembership",
    "WorkspaceOperation",
    "WorkspaceRecord",
    "WorkspaceRuntimeBinding",
    "WorkspaceSyncStatus",
    "WorkspaceTransferPolicy",
    "WorkspaceTreeConversation",
    "WorkspaceTreeWorkspace",
    "build_console_conversation_browser_state",
    "build_workspace_tree_state",
    "build_library_workspace_depth_state",
    "library_item_context_handoff",
    "build_console_workspace_state",
    "console_persisted_row_updated_sort",
    "console_conversation_starred_recency_sort_key",
    "overlay_console_conversation_markers",
    "console_workspace_conversation_result_copy",
    "console_workspace_conversation_visible_rows",
    "evaluate_workspace_eligibility",
    "update_workspace_tree_conversation",
]
