# Egyptian Hieroglyphs splash card
# Place this file in ~/.config/tldw_cli/splash_cards/

type = "animated"
effect = "ascii_morph"
style = "rgb(255,215,0) on rgb(25,20,15)"

# ASCII morph effect parameters
hieroglyph_translation = true
papyrus_texture = 0.8
ancient_fade = 0.9

content = """
╔═══════════════════════════════════════════════════════╗
║          𓂀 BOOK OF THE DIGITAL DEAD 𓂀               ║
╠═══════════════════════════════════════════════════════╣
║                                                       ║
║  𓊹𓊺𓊻  𓏏𓃭𓂧𓍯  𓎗𓃭𓄿𓏏𓃀𓊮𓊮𓎗                         ║
║  ┌─────────────────────────────────────────┐         ║
║  │ "As the sacred scarab rolls the sun     │         ║
║  │  So does TLDW process your data"        │ 𓁿       ║
║  │                                          │ ☥       ║
║  │  Loading: ▓▓▓▓▓▓▓▓░░░░░░░ 42%          │ 𓊽       ║
║  └─────────────────────────────────────────┘         ║
║                                                       ║
║      𓈖𓆎𓅓  ANUBIS GUARDS YOUR PROCESSES  𓈖𓆎𓅓         ║
║                                                       ║
║  ┌───┐ ┌───┐ ┌───┐ ┌───┐ ┌───┐ ┌───┐ ┌───┐         ║
║  │ 𓀀 │ │ 𓁶 │ │ 𓁷 │ │ 𓁹 │ │ 𓂋 │ │ 𓃀 │ │ 𓄿 │         ║
║  └───┘ └───┘ └───┘ └───┘ └───┘ └───┘ └───┘         ║
║                                                       ║
╚═══════════════════════════════════════════════════════╝
"""

# Progress messages
progress_messages = [
    "Deciphering ancient protocols...",
    "Invoking protection of Thoth...",
    "Translating hieroglyphic bytecode...",
    "Crossing the digital Nile...",
    "Awakening silicon mummies..."
]

# Additional styling
css_classes = ["papyrus-scroll", "pharaoh-gold"]