"""TASK-18514: probe HyDE against the pre-registered bar, before building it.

Run::

    RAG_EVAL=1 PYTHONPATH=$(pwd) <venv>/bin/python \
        Docs/superpowers/qa/2026-08-18-hyde-census/hyde_probe.py

HyDE replaces the QUERY EMBEDDING with the embedding of a hypothetical answer
document generated by an LLM. This probe implements exactly that and nothing
else: the generated passage is passed as the search text in `semantic` mode,
so the only thing that changes between arms is the vector the index is
searched with.

**Measured in `semantic` only, deliberately.** In `hybrid` the same string
also feeds the FTS leg, which is NOT what HyDE means -- a faithful hybrid
HyDE would send the passage to the vector leg and the original query to the
keyword leg, which is a production change this probe is not licensed to make.
Semantic is also where the reachable population lives (11 of 11 per the
census).

Generations are cached to `generations.json` beside this file so the run is
reproducible and the generator's actual output is auditable rather than
summarized.
"""
from __future__ import annotations

import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

HERE = Path(__file__).resolve().parent
CACHE = HERE / "generations.json"

def _validated_endpoint(raw: str) -> str:
    """Validate the generator endpoint before any request is built.

    Args:
        raw: Candidate URL, from ``HYDE_ENDPOINT`` or the default.

    Returns:
        The URL unchanged.

    Raises:
        SystemExit: The value is not an http(s) URL with a host. A silently
            malformed endpoint would surface later as "the generator returned
            nothing", which this programme has repeatedly mistaken for a
            measured negative.
    """
    parsed = urllib.parse.urlparse(raw)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        raise SystemExit(
            f"HYDE_ENDPOINT must be an http(s) URL with a host; got {raw!r}"
        )
    return raw


def _validated_model(raw: str) -> str:
    """Validate the model id.

    Args:
        raw: Candidate model id, from ``HYDE_MODEL`` or the default.

    Returns:
        The stripped model id.

    Raises:
        SystemExit: The value is blank.
    """
    if not raw or not raw.strip():
        raise SystemExit("HYDE_MODEL must be a non-empty model id")
    return raw.strip()


ENDPOINT = _validated_endpoint(
    os.environ.get("HYDE_ENDPOINT", "http://localhost:9099/v1/chat/completions")
)
MODEL = _validated_model(
    os.environ.get("HYDE_MODEL", "gemma-4-26B-A4B-it-ultra-uncensored-heretic-Q4_K_M.gguf")
)
K = 10
BAR = 5             # registered in TASK-18514 before any measurement
MODE = "semantic"
MAX_TOKENS = 220    # generation budget; also reported in the run header
GEN_TIMEOUT_S = 180

#: Deliberately plain. A prompt tuned against these 60 queries would measure
#: the prompt, not HyDE.
PROMPT = (
    "Write a short passage that would appear in a document answering the "
    "question below. Write it as a factual excerpt, not as an answer to a "
    "person. Do not restate the question. Output only the passage.\n\n"
    "Question: {q}"
)


def generate(query: str) -> str:
    """Generate one hypothetical document.

    Args:
        query: The golden query text.

    Returns:
        The generated passage, stripped. Empty string if the server returned
        no content (reported, never silently treated as a passage).

    Raises:
        urllib.error.URLError: The generator endpoint is unreachable.
        TimeoutError: The request exceeded ``GEN_TIMEOUT_S``.
        KeyError: The response lacked the expected OpenAI-shaped fields.
    """
    payload = {
        "model": MODEL,
        "messages": [{"role": "user", "content": PROMPT.format(q=query)}],
        "temperature": 0,
        "max_tokens": MAX_TOKENS,
        # This server fronts a REASONING model: without this it spends the
        # whole budget in `reasoning_content` and returns content="".
        "chat_template_kwargs": {"enable_thinking": False},
    }
    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=GEN_TIMEOUT_S) as resp:
        body = json.loads(resp.read())
    msg = body["choices"][0]["message"]
    return (msg.get("content") or "").strip()


def score_arms(
    relevant: dict[str, bool],
    base: dict[str, bool],
    hyde: dict[str, bool],
    empty_ids: set[str],
) -> tuple[list[str], list[str], list[str], list[str]]:
    """Partition queries into scored / unmeasurable / gains / losses.

    Args:
        relevant: query id -> whether the query has any ground-truth target.
        base: query id -> baseline hit at k.
        hyde: query id -> HyDE-arm hit at k (absent when the arm did not run).
        empty_ids: query ids whose generation came back empty.

    Returns:
        ``(scored, unmeasurable, gains, losses)``.

        A query with no target is excluded (a `negative`: a miss is correct).
        A query with an EMPTY generation is excluded too — its HyDE arm never
        ran, and scoring it as a miss would turn an unmeasurable query into a
        LOSS, corrupting the harm gate. That is this programme's recurring
        defect: "could not measure" rendering identically to "measured, and it
        got worse".
    """
    targeted = [q for q, has in relevant.items() if has]
    unmeasurable = sorted(q for q in targeted if q in empty_ids)
    scored = sorted(q for q in targeted if q not in empty_ids)
    gains = [q for q in scored if hyde.get(q) and not base.get(q)]
    losses = [q for q in scored if base.get(q) and not hyde.get(q)]
    return scored, unmeasurable, gains, losses


def main() -> int:
    """Probe HyDE and print gains, losses and the harm gate.

    Returns:
        0 on a complete run; 1 if the population was incomplete.
    """
    import tempfile

    if os.environ.get("RAG_EVAL") != "1":
        raise SystemExit("refusing to run without RAG_EVAL=1 (this builds a real index)")

    import tldw_chatbook
    from tldw_chatbook.Library.library_local_rag_search_service import (
        LibraryLocalRagSearchService,
    )

    from Tests.RAG_Eval.harness.canonicalize import rows_to_doc_ids, slug_lookup_from
    from Tests.RAG_Eval.harness.goldenset import load_fixtures
    from Tests.RAG_Eval.harness.ingest import build_eval_runtime
    from Tests.RAG_Eval.harness.runner import (
        SOURCE_TYPES,
        _extract_rows,
        build_query_scope,
    )

    print(f"PROVENANCE tldw_chatbook <- {tldw_chatbook.__file__}")
    assert str(REPO) in tldw_chatbook.__file__, f"WRONG TREE: expected under {REPO}"
    print(f"GENERATOR endpoint={ENDPOINT}\nGENERATOR model={MODEL}")
    print(
        f"GENERATOR decoding: temperature=0, max_tokens={MAX_TOKENS}, "
        "enable_thinking=False"
    )

    corpus, golden = load_fixtures()

    # ---- generate (cached) ----
    cache: dict[str, str] = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    todo = [q for q in golden if q.id not in cache]
    if todo:
        print(f"\ngenerating {len(todo)} hypothetical documents...")
        t0 = time.time()
        for i, q in enumerate(todo, 1):
            try:
                cache[q.id] = generate(q.query)
            except (urllib.error.URLError, TimeoutError, KeyError) as exc:
                print(f"  !! {q.id}: {type(exc).__name__}: {exc}")
                cache[q.id] = ""
            if i % 10 == 0 or i == len(todo):
                print(f"  {i}/{len(todo)}  ({time.time()-t0:.0f}s)")
        CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True))
    empty = [qid for qid, txt in cache.items() if not txt.strip()]
    print(f"\nPROBE PROOF: generations={len(cache)}, EMPTY={len(empty)} {empty}")
    print(f"PROBE PROOF: mean generated words = "
          f"{sum(len(t.split()) for t in cache.values()) / max(len(cache),1):.0f}")
    if empty:
        print("  NOTE: an empty generation makes that query's HyDE arm meaningless;")
        print("        it is reported, never scored as a HyDE result.")

    # ---- retrieve, both arms ----
    errors: list[str] = []
    base: dict[str, bool] = {}
    hyde: dict[str, bool] = {}
    with tempfile.TemporaryDirectory() as tmp:
        rt = build_eval_runtime(corpus, tmp)
        seam = LibraryLocalRagSearchService(rt.app)
        lookup = slug_lookup_from(rt.slug_to_source)
        cfg = rt.service.config.search
        original = getattr(cfg, "default_search_mode", None)
        cfg.default_search_mode = MODE
        try:
            for q in golden:
                scope = build_query_scope(rt.slug_to_source, q)
                for arm, text in (("base", q.query), ("hyde", cache.get(q.id, ""))):
                    if arm == "hyde" and not text.strip():
                        # An empty generation means the HyDE arm never RAN for
                        # this query. Scoring it False would convert an
                        # unmeasurable query into a LOSS and corrupt the harm
                        # gate -- "could not measure" rendering as "measured,
                        # and it got worse". Excluded from scoring, reported.
                        continue
                    try:
                        res = rt.run(
                            seam.search(text, SOURCE_TYPES, "rag", top_k=K, scope=scope)
                        )
                        rows, _b, err = _extract_rows(res)
                    except Exception as exc:                       # noqa: BLE001
                        rows, err = [], f"{type(exc).__name__}: {exc}"
                    if err:
                        errors.append(f"{arm}/{q.id}: {err}")
                        (base if arm == "base" else hyde)[q.id] = False
                        continue
                    docs = set(rows_to_doc_ids(rows, lookup))
                    (base if arm == "base" else hyde)[q.id] = any(
                        s in docs for s in q.relevant_slugs
                    )
        finally:
            cfg.default_search_mode = original

    print(f"\nPROBE PROOF: errors = {len(errors)}")
    for e in errors[:10]:
        print(f"    !! {e}")
    if errors:
        print("NO VERDICT CLAIMED -- population incomplete.")
        return 1

    by_id = {q.id: q for q in golden}
    # Negatives have no target; queries whose generation came back empty have
    # no HyDE arm at all and are excluded rather than scored as losses.
    empty_ids = {qid for qid, txt in cache.items() if not txt.strip()}
    scored, unmeasurable, gains, losses = score_arms(
        {q.id: bool(q.relevant_slugs) for q in golden}, base, hyde, empty_ids
    )
    print(f"\n=== HyDE vs baseline, mode={MODE}, k={K} "
          f"({len(scored)} target-bearing queries scored) ===")
    if unmeasurable:
        print(f"  EXCLUDED, empty generation (no HyDE arm ran): "
              f"{len(unmeasurable)} {unmeasurable}")
        print("    -- reported, NOT scored as losses: an unmeasurable query is")
        print("       not a query that got worse.")
    print(f"  baseline hits : {sum(base[q] for q in scored)}")
    print(f"  HyDE hits     : {sum(hyde[q] for q in scored)}")
    print(f"\n  GAINS  ({len(gains)}):")
    for qid in gains:
        print(f"      + {qid:32s} [{by_id[qid].category}]")
    print(f"\n  LOSSES ({len(losses)}):")
    for qid in losses:
        print(f"      - {qid:32s} [{by_id[qid].category}]")

    # negatives: HyDE must not start pulling documents for queries with no target
    negs = [q.id for q in golden if not q.relevant_slugs]
    print(f"\n  negative queries (no target; reported, not scored): {len(negs)}")

    print(f"\n=== VERDICT vs the pre-registered bar ===")
    print(f"  clause 1 -- rescues >= {BAR}          : {len(gains)} -> "
          f"{'PASS' if len(gains) >= BAR else 'FAIL'}")
    print(f"  clause 2 -- zero hitters lose target : {len(losses)} -> "
          f"{'PASS' if not losses else 'FAIL'}")
    verdict = len(gains) >= BAR and not losses
    print(f"  RESULT: {'ADMIT candidate' if verdict else 'NULL -- HyDE not admitted'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
