#!/usr/bin/env python3
"""Deliberately regenerate the boot-budget ratchet snapshots (ADR-097).

The four boot-budget guards (``Tests/Performance/test_app_import_weight.py``,
``test_ui_ready_module_census.py``, ``test_boot_css_byte_budget.py``,
``test_screen_preimport_payload_budget.py``) diff their measurements against
pinned snapshots in ``Tests/Performance/boot_budget_snapshots/`` so a breach
names the culprit. This script is the ONLY writer of those snapshots -- the
guards never write, so a snapshot cannot be regenerated by accident.

Usage (from the repo root, after any PR that legitimately moves a boot cost)::

    .venv/bin/python scripts/update_boot_budget_snapshots.py
    .venv/bin/python scripts/update_boot_budget_snapshots.py --only css --only preimport

Guards: ``import-weight`` (~5 s), ``css`` (~2 s), ``preimport`` (~30 s),
``ui-ready`` (two full headless boots; 1-3 min).

The script REFUSES to pin a snapshot whose measurement is over its ratchet
limit: blessing an over-budget state would empty the very diff the snapshot
exists to feed. ``--force`` overrides, for capturing evidence of a breach.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
import tempfile
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parents[1]
PERF_DIR = REPO_ROOT / "Tests" / "Performance"

# The guards import `tldw_chatbook.*`; inside pytest, Tests/conftest.py puts
# the repo root on sys.path -- here we must do it ourselves.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

GUARDS = ("import-weight", "ui-ready", "css", "preimport")


def _isolate_config() -> None:
    """Point HOME/XDG/TLDW_CONFIG_PATH at scratch dirs before any app import.

    The css census imports ``tldw_chatbook.app`` IN-PROCESS; outside pytest
    there is no conftest isolation, and an app import against the developer's
    real HOME writes to the live config (a recorded incident -- see
    'verification probes need config isolation').
    """
    scratch = Path(tempfile.mkdtemp(prefix="tldw_budget_snapshots_"))
    for name in ("home", "data", "config"):
        (scratch / name).mkdir()
    os.environ.update(
        {
            "HOME": str(scratch / "home"),
            "USERPROFILE": str(scratch / "home"),
            "XDG_DATA_HOME": str(scratch / "data"),
            "XDG_CONFIG_HOME": str(scratch / "config"),
            "TLDW_CONFIG_PATH": str(scratch / "config" / "config.toml"),
            "TLDW_TEST_MODE": "1",
        }
    )


def _load_by_path(name: str, path: Path) -> ModuleType:
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None, f"unloadable: {path}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _ratchet():
    return _load_by_path(
        "tldw_tests_boot_budget_ratchet", PERF_DIR / "boot_budget_ratchet.py"
    )


def _write(path: Path, content: str, label: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {label}: {path.relative_to(REPO_ROOT)}")


def _refuse_over_budget(
    guard: str, measured: int, limit: int, constant: str, force: bool
) -> bool:
    """Refuse to bless an over-budget measurement (unless --force).

    Returns:
        True if the caller must skip writing this snapshot.
    """
    if measured <= limit or force:
        return False
    print(
        f"REFUSING to pin {guard}: measured {measured} exceeds the ratchet "
        f"limit {limit} ({constant}). Pinning an over-budget state would "
        "hide the culprits behind a blessed baseline. Shed the cost first "
        "(ADR-097), or pass --force to capture breach evidence.",
        file=sys.stderr,
    )
    return True


def update_import_weight(force: bool) -> bool:
    mod = _load_by_path(
        "tldw_perf_test_app_import_weight", PERF_DIR / "test_app_import_weight.py"
    )
    with tempfile.TemporaryDirectory() as td:
        payload = mod._measure_app_import(Path(td))
    count = payload["tldw_module_count"]
    if _refuse_over_budget(
        "import-weight",
        count,
        mod.MAX_TLDW_MODULE_COUNT - 1,  # the guard asserts strictly less-than
        "MAX_TLDW_MODULE_COUNT",
        force,
    ):
        return False
    ratchet = _ratchet()
    header = (
        "# tldw_chatbook.* modules resident after `import tldw_chatbook.app`.\n"
        f"# {count} modules. Written ONLY by "
        "scripts/update_boot_budget_snapshots.py (ADR-097).\n"
    )
    _write(
        ratchet.SNAPSHOT_DIR / ratchet.SNAPSHOT_FILES["boot-import-weight"],
        header + "\n".join(payload["tldw_modules"]) + "\n",
        f"boot-import-weight snapshot ({count} modules)",
    )
    return True


def update_ui_ready(force: bool) -> bool:
    mod = _load_by_path(
        "tldw_perf_test_ui_ready_module_census",
        PERF_DIR / "test_ui_ready_module_census.py",
    )
    with tempfile.TemporaryDirectory() as td:
        mods = mod._boot_and_census(Path(td))
    if _refuse_over_budget(
        "ui-ready",
        len(mods),
        mod.MAX_TLDW_MODULES_AT_UI_READY,
        "MAX_TLDW_MODULES_AT_UI_READY",
        force,
    ):
        return False
    ratchet = _ratchet()
    header = (
        "# tldw_chatbook.* modules resident at _ui_ready (warm second boot).\n"
        f"# {len(mods)} modules; warm boots wobble +/-1 (see the guard's "
        "docstring). Written ONLY by "
        "scripts/update_boot_budget_snapshots.py (ADR-097).\n"
    )
    _write(
        ratchet.SNAPSHOT_DIR / ratchet.SNAPSHOT_FILES["ui-ready-census"],
        header + "\n".join(mods) + "\n",
        f"ui-ready-census snapshot ({len(mods)} modules)",
    )
    return True


def update_css(force: bool) -> bool:
    mod = _load_by_path(
        "tldw_perf_test_boot_css_byte_budget",
        PERF_DIR / "test_boot_css_byte_budget.py",
    )
    per_source = mod._boot_parsed_css_census()
    total = sum(per_source.values())
    if _refuse_over_budget(
        "css", total, mod.MAX_BOOT_PARSED_CSS_BYTES, "MAX_BOOT_PARSED_CSS_BYTES", force
    ):
        return False
    ratchet = _ratchet()
    payload = {
        "_comment": (
            "Boot-parsed CSS byte census. Written ONLY by "
            "scripts/update_boot_budget_snapshots.py (ADR-097)."
        ),
        "total": total,
        "per_source": dict(sorted(per_source.items())),
        "per_segment": dict(sorted(mod._boot_parsed_css_segment_census().items())),
    }
    _write(
        ratchet.SNAPSHOT_DIR / ratchet.SNAPSHOT_FILES["boot-css-bytes"],
        json.dumps(payload, indent=2) + "\n",
        f"boot-css-bytes snapshot ({total:,} B)",
    )
    return True


def update_preimport(force: bool) -> bool:
    mod = _load_by_path(
        "tldw_perf_test_screen_preimport_payload_budget",
        PERF_DIR / "test_screen_preimport_payload_budget.py",
    )
    with tempfile.TemporaryDirectory() as td:
        census = mod._run_census(Path(td))
    over = _refuse_over_budget(
        "preimport",
        census["pass_added_modules"],
        mod.MAX_PASS_ADDED_MODULES,
        "MAX_PASS_ADDED_MODULES",
        force,
    ) or _refuse_over_budget(
        "preimport",
        census["pass_added_loc"],
        mod.MAX_PASS_ADDED_LOC,
        "MAX_PASS_ADDED_LOC",
        force,
    )
    if over:
        return False
    ratchet = _ratchet()
    payload = {
        "_comment": (
            "Screen pre-importer payload census. Written ONLY by "
            "scripts/update_boot_budget_snapshots.py (ADR-097)."
        ),
        "pass_added_modules": census["pass_added_modules"],
        "pass_added_loc": census["pass_added_loc"],
        "routes": {
            row["route"]: {"loc": row["added_loc"], "modules": row["modules"]}
            for row in sorted(census["routes"], key=lambda r: r["route"])
        },
    }
    _write(
        ratchet.SNAPSHOT_DIR / ratchet.SNAPSHOT_FILES["preimport-payload"],
        json.dumps(payload, indent=2) + "\n",
        (
            f"preimport-payload snapshot ({census['pass_added_modules']} "
            f"modules / {census['pass_added_loc']:,} LOC)"
        ),
    )
    return True


UPDATERS = {
    "import-weight": update_import_weight,
    "ui-ready": update_ui_ready,
    "css": update_css,
    "preimport": update_preimport,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--only",
        action="append",
        choices=GUARDS,
        help="Regenerate only this guard's snapshot (repeatable).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Pin even an over-budget measurement (breach evidence only).",
    )
    args = parser.parse_args()

    _isolate_config()
    selected = args.only or list(GUARDS)
    failures = [name for name in selected if not UPDATERS[name](args.force)]
    if failures:
        print(f"refused/failed: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
