"""Provider-neutral speech-to-text contracts."""

from .contracts import (
    MAX_BUFFER_AUDIO_BYTES,
    BufferAudioSource,
    CancellationGranularity,
    CancellationToken,
    ExecutionDevice,
    FileAudioSource,
    InputKind,
    LanguageInputMode,
    PipelineCapabilities,
    PrivacyRequirements,
    ProducedCapabilities,
    ProgressSink,
    TimestampGranularity,
    TranscriptionPhase,
    TranscriptionProgress,
    TranscriptionProvenance,
    TranscriptionRequest,
    TranscriptionResult,
    TranscriptionSegment,
    TranscriptionTask,
    TranscriptionTimings,
    TranscriptionWarningCode,
)

__all__ = [
    "MAX_BUFFER_AUDIO_BYTES",
    "BufferAudioSource",
    "CancellationGranularity",
    "CancellationToken",
    "ExecutionDevice",
    "FileAudioSource",
    "InputKind",
    "LanguageInputMode",
    "PipelineCapabilities",
    "PrivacyRequirements",
    "ProducedCapabilities",
    "ProgressSink",
    "TimestampGranularity",
    "TranscriptionPhase",
    "TranscriptionProgress",
    "TranscriptionProvenance",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionSegment",
    "TranscriptionTask",
    "TranscriptionTimings",
    "TranscriptionWarningCode",
]
