"""Durable recovered-media payloads and references (ADR-126).

Each operation holds its native catalog connection through file publication or
retirement. A committed journal row survives interruption; no age-based cleanup
or temporary-media resolver is allowed to reinterpret a known reference.
"""

import hashlib
import json
import re
import sqlite3
import stat
import uuid
from contextlib import closing, contextmanager
from dataclasses import dataclass
from pathlib import Path

from tldw_chatbook.DB.private_sqlite import connect_private_sqlite
from tldw_chatbook.DB.recovery_sqlite import _validate_sqlite
from tldw_chatbook.Utils.platform_files import os
from tldw_chatbook.Utils.private_paths import (
    _open_verified_parent,
    atomic_private_write_bytes,
    lexical_path,
    open_private_binary,
    secure_private_directory,
)

from .participants import _core_access, _register_core_connection
from .recovered_media_schema import SCHEMAS, migrate, schema_policy

MAX_PAYLOAD_BYTES = 512 * 1024 * 1024
_ASSET_ID = re.compile(r"^[0-9a-f]{32}$")


def _recovered_alias_authorizer(read_authorizer):
    """Permit only installed reference aliases within a private relocation."""

    def authorize(action, first, second, database, source):
        if source is None and (
            action == sqlite3.SQLITE_TRANSACTION
            and database is None
            and first in {"BEGIN", "COMMIT", "ROLLBACK"}
            or database == "main"
            and (
                action == sqlite3.SQLITE_INSERT
                and first == "refs"
                or action == sqlite3.SQLITE_UPDATE
                and (first, second) == ("tombstones", "references_json")
            )
        ):
            return sqlite3.SQLITE_OK
        return read_authorizer(action, first, second, database, source)

    return authorize


def _identity(profile, message, slug, media_type):
    values = (profile, message, slug, media_type)
    if any(
        type(value) is not str or not value or len(value) > 4096 for value in values
    ):
        raise ValueError("invalid_recovered_reference")
    if not media_type.startswith(("image/", "video/")):
        raise ValueError("invalid_recovered_media_type")
    return values


def _read(path):
    with open_private_binary(path) as opened:
        if not opened.result.verified_private:
            raise ValueError("recovered_media_privacy_unverified")
        payload = opened.stream.read(MAX_PAYLOAD_BYTES + 1)
    if len(payload) > MAX_PAYLOAD_BYTES:
        raise ValueError("recovered_media_too_large")
    return payload


@dataclass(frozen=True)
class TemporaryMediaSource:
    """One already captured payload, with an optional real transcript identity."""

    logical_id: str
    path: Path
    media_type: str
    reference: tuple[str, str, str, str] | None = None


def _read_captured_media(scope, path, limit, cancel):
    """Read a stable private staged member through the held capture boundary."""
    from .archive_reader import _check, _identity, _regular
    from .storage_admission import _check_capture_file_identity

    scope.check()
    path = lexical_path(path)
    if scope.staging not in path.parents or path.resolve() != path:
        raise ValueError("temporary_capture_path_invalid")
    with _regular(path) as stream:
        before = os.fstat(stream.fileno())
        _check_capture_file_identity(scope, path, before)
        if before.st_mode & 0o077 or before.st_size > limit:
            raise ValueError("temporary_capture_member_limit")
        _check(cancel)
        payload = stream.read(limit + 1)
        _check(cancel)
        if (
            len(payload) > limit
            or _identity(before) != _identity(os.fstat(stream.fileno()))
            or _identity(before) != _identity(os.stat(path, follow_symlinks=False))
        ):
            raise ValueError("temporary_capture_source_changed")
    return payload


def materialize_temporary_media(session, root, sources, *, cancel, limits, byte_budget):
    """Build retained representation only inside this held capture's private stage.

    The capture caller selects sources from its original inventory. This helper
    never discovers or admits source paths, and never changes a live TTL store.
    Generated bytes precede final catalog references; a failed private candidate
    remains unusable until its caller discards it.
    """
    from . import storage_admission as storage
    from .archive_reader import _check
    from .limits import ArchiveLimits
    from .native_files import (
        create_private_directory,
        create_private_file,
        pinned_directory,
    )
    from .space import require_capacity

    scope = getattr(storage._local, "capture_scope", None)
    if scope is None or scope.session is not session:
        raise ValueError("temporary_capture_scope_required")
    scope.check()
    if (
        type(limits) is not ArchiveLimits
        or type(byte_budget) is not int
        or not 0 < byte_budget <= scope.byte_budget
        or type(sources) is not tuple
        or len(sources) > limits.members
    ):
        raise ValueError("temporary_capture_budget_invalid")
    root = lexical_path(root)
    if scope.staging not in root.parents or root.resolve() != root:
        raise ValueError("temporary_capture_path_invalid")
    if len({source.logical_id for source in sources}) != len(sources):
        raise ValueError("temporary_capture_source_duplicate")
    payloads = []
    total = 0
    for source in sources:
        _check(cancel)
        if (
            type(source) is not TemporaryMediaSource
            or not source.logical_id
            or not source.media_type.startswith(("image/", "video/"))
        ):
            raise ValueError("temporary_capture_source_invalid")
        if source.reference is not None and (
            _identity(*source.reference)[3] != source.media_type
        ):
            raise ValueError("temporary_capture_reference_invalid")
        path = lexical_path(source.path)
        if scope.staging not in path.parents or path.resolve() != path:
            raise ValueError("temporary_capture_path_invalid")
        info = os.stat(path, follow_symlinks=False)
        storage._check_capture_file_identity(scope, path, info)
        if info.st_size > min(limits.member_bytes, MAX_PAYLOAD_BYTES):
            raise ValueError("temporary_capture_member_limit")
        total += info.st_size
        if total > byte_budget:
            raise ValueError("temporary_capture_byte_limit")
        payloads.append(source)
    require_capacity({root: total})
    if not root.exists():
        create_private_directory(root)
    with pinned_directory(root) as parent:
        if os.fstat(parent).st_mode & 0o077:
            raise ValueError("recovered_media_privacy_unverified")
    catalog = root / "catalog.sqlite3"
    if catalog.exists():
        if os.stat(catalog).st_size > min(limits.member_bytes, byte_budget):
            raise ValueError("temporary_capture_member_limit")
        storage._check_capture_file_identity(
            scope, catalog, os.stat(catalog, follow_symlinks=False)
        )
    with closing(
        connect_private_sqlite("recovery.recovered_media", catalog)
    ) as connection:
        connection.execute("PRAGMA foreign_keys=ON")
        migrate(connection)
        issues = _RecoveredAdapter._validate_connection(connection)
        if issues:
            raise ValueError(issues[0])
        for asset, digest, size in connection.execute(
            "SELECT asset_id,digest,size FROM assets WHERE state='ready'"
        ):
            previous = _read_captured_media(
                scope,
                root / (asset + ".payload"),
                min(limits.member_bytes, MAX_PAYLOAD_BYTES),
                cancel,
            )
            if (hashlib.sha256(previous).hexdigest(), len(previous)) != (digest, size):
                raise ValueError("recovered_payload_missing")
            total += size
        if total + os.stat(catalog).st_size > byte_budget:
            raise ValueError("temporary_capture_byte_limit")
        result = {}
        with connection:
            connection.execute("BEGIN IMMEDIATE")
            for source in payloads:
                _check(cancel)
                payload = _read_captured_media(
                    scope,
                    source.path,
                    min(limits.member_bytes, MAX_PAYLOAD_BYTES),
                    cancel,
                )
                digest = hashlib.sha256(payload).hexdigest()
                previous = (
                    connection.execute(
                        "SELECT a.asset_id,a.digest,a.size,a.state FROM refs r JOIN assets a USING(asset_id) WHERE profile=? AND message=? AND slug=? AND r.media_type=?",
                        source.reference,
                    ).fetchone()
                    if source.reference is not None
                    else None
                )
                if previous:
                    if previous[3] == "deleted":
                        result[source.logical_id] = previous[0]
                        continue
                    if previous[1:3] != (digest, len(payload)):
                        raise ValueError("recovered_reference_collision")
                    result[source.logical_id] = previous[0]
                    continue
                asset = uuid.uuid4().hex
                destination = root / (asset + ".payload")
                if destination.exists() or destination.is_symlink():
                    raise FileExistsError("recovered_asset_id_collision")
                with create_private_file(destination) as descriptor:
                    remaining = memoryview(payload)
                    while remaining:
                        _check(cancel)
                        written = os.write(descriptor, remaining)
                        if written <= 0:
                            raise OSError("temporary_capture_write_failed")
                        remaining = remaining[written:]
                if (
                    _read_captured_media(
                        scope,
                        destination,
                        min(limits.member_bytes, MAX_PAYLOAD_BYTES),
                        cancel,
                    )
                    != payload
                ):
                    raise ValueError("recovered_payload_missing")
                connection.execute(
                    "INSERT INTO assets VALUES (?,?,?,?, 'ready')",
                    (asset, digest, len(payload), source.media_type),
                )
                if source.reference is not None:
                    connection.execute(
                        "INSERT INTO refs VALUES (?,?,?,?,?)",
                        source.reference + (asset,),
                    )
                result[source.logical_id] = asset
            issues = _RecoveredAdapter._validate_connection(connection)
            if issues:
                raise ValueError(issues[0])
            count, size = connection.execute(
                "SELECT COUNT(*),COALESCE(SUM(size),0) FROM assets WHERE state='ready'"
            ).fetchone()
            catalog_size = (
                connection.execute("PRAGMA page_count").fetchone()[0]
                * connection.execute("PRAGMA page_size").fetchone()[0]
            )
            if catalog_size > limits.member_bytes:
                raise ValueError("temporary_capture_member_limit")
            if count + 1 > limits.members or size + catalog_size > byte_budget:
                raise ValueError("temporary_capture_byte_limit")
        scope.check()
    if os.stat(catalog).st_size > limits.member_bytes:
        raise ValueError("temporary_capture_member_limit")
    return result


def prepare_temporary_capture(
    session, inventory, staged, *, stage, cancel, limits, byte_budget
):
    """Transform only installed captured TEMP members into recovered owner records.

    The returned inventory describes archive representation only. The caller must
    retain its original inventory for source admission and final rediscovery.
    """
    from dataclasses import replace

    from tldw_chatbook.Video_Generation.video_metadata import video_relative_path

    from . import storage_admission as storage
    from .archive_reader import _check
    from .models import DiscoveryContext, FileMetadata, StorageItem
    from .native_files import create_private_directory, create_private_file
    from .owner_registry import registered
    from .recovery_files import _tree_member_id

    scope = getattr(storage._local, "capture_scope", None)
    if scope is None or scope.session is not session:
        raise ValueError("temporary_capture_scope_required")
    scope.check()
    adapters = {owner.owner_id: owner for owner in registered()}
    candidates = {item.logical_id: path for item, path in staged}
    represented = {item.logical_id: item for item in inventory.items}
    removed, additions = set(), []
    retained = unavailable = kept_deleted = 0
    for config in inventory.items:
        if config.owner != "config" or config.status != "included":
            continue
        profile = config.logical_id.split(":")[1]
        context = DiscoveryContext(config.path, profile)
        prefix = f"profile:{profile}:"
        local = tuple(
            item for item in inventory.items if item.logical_id.startswith(prefix)
        )
        generated = tuple(item for item in local if item.owner == "generation.assets")
        roots = {
            item.path.name: item.path
            for item in generated
            if item.path is not None
            and item.metadata is not None
            and item.metadata.kind == "directory"
            and item.metadata.parent_id is None
        }
        images, videos = roots.get("generated_images"), roots.get("generated_videos")
        temporary = tuple(
            item
            for item in generated
            if item.path is not None
            and (
                images is not None
                and (
                    item.path == images / "temp" or images / "temp" in item.path.parents
                )
                or videos is not None
                and (item.path == videos or videos in item.path.parents)
            )
            and item.status in {"included", "included_directory"}
        )
        by_path = {item.path: item for item in temporary if item.status == "included"}
        references = {}
        primary = next(
            (
                item
                for item in local
                if item.owner == "db.chachanotes.primary" and item.status == "included"
            ),
            None,
        )
        if primary is not None:
            for message, slug, media_type in adapters[
                primary.owner
            ].temporary_video_references(
                candidates[primary.logical_id],
                cancel=cancel,
                max_records=limits.members,
                max_metadata_bytes=min(16 * 1024**2, byte_budget),
            ):
                path = (
                    None
                    if videos is None
                    else videos
                    / video_relative_path(message, slug, media_type.split("/")[1])
                )
                if path not in by_path:
                    unavailable += 1
                    continue
                references[path] = (profile, message, slug, media_type)
        sources = []
        for item in temporary:
            removed.add(item.logical_id)
            represented[item.logical_id] = replace(
                item, status="intentionally_excluded"
            )
            if item.status != "included":
                continue
            reference = references.get(item.path)
            if images is not None and images / "temp" in item.path.parents:
                if item.path.suffix.lower() != ".png":
                    raise ValueError("temporary_media_type_unsupported")
                media_type = "image/png"
            else:
                relative = item.path.relative_to(videos)
                if len(relative.parts) != 2 or item.path.suffix not in {
                    ".mp4",
                    ".webm",
                }:
                    raise ValueError("temporary_video_member_unsupported")
                if (
                    video_relative_path(
                        relative.parts[0], item.path.stem, item.path.suffix[1:]
                    )
                    != relative
                ):
                    raise ValueError("temporary_video_member_unsupported")
                media_type = "video/" + item.path.suffix[1:]
            sources.append(
                TemporaryMediaSource(
                    item.logical_id, candidates[item.logical_id], media_type, reference
                )
            )
        if not sources:
            continue
        old = tuple(item for item in local if item.owner == "recovered.media")
        root_item = next(
            (
                item
                for item in old
                if item.path is not None
                and (
                    item.metadata is not None
                    and item.metadata.kind == "directory"
                    and item.metadata.parent_id is None
                    or item.status == "unused"
                    and item.path.name == "recovered_media"
                )
            ),
            None,
        )
        if root_item is None:
            raise ValueError("temporary_recovered_root_unavailable")
        canonical = root_item.path
        root = stage / "payload" / ("retained-" + profile)
        create_private_directory(root)
        for item in old:
            if item.status != "included":
                continue
            if item.metadata is None or item.metadata.root_id != root_item.logical_id:
                raise ValueError("invalid_recovered_role")
            payload = _read_captured_media(
                scope, candidates[item.logical_id], limits.member_bytes, cancel
            )
            with create_private_file(root / item.metadata.relative_path) as descriptor:
                view = memoryview(payload)
                while view:
                    _check(cancel)
                    written = os.write(descriptor, view)
                    if written <= 0:
                        raise OSError("temporary_capture_write_failed")
                    view = view[written:]
        materialized = materialize_temporary_media(
            session,
            root,
            tuple(sources),
            cancel=cancel,
            limits=limits,
            byte_budget=byte_budget,
        )
        owner = adapters["recovered.media"]
        catalog = root / "catalog.sqlite3"
        with closing(
            connect_private_sqlite("recovery.recovered_media", catalog, read_only=True)
        ) as connection:
            names = ["catalog.sqlite3"] + [
                row[0] + ".payload"
                for row in connection.execute(
                    "SELECT asset_id FROM assets WHERE state='ready' ORDER BY asset_id"
                )
            ]
        ready_names = set(names[1:])
        ready_count = sum(
            asset + ".payload" in ready_names for asset in materialized.values()
        )
        retained += ready_count
        kept_deleted += len(materialized) - ready_count
        root_id = _tree_member_id(context, owner.owner_id, canonical, canonical)
        if root_id != root_item.logical_id:
            raise ValueError("temporary_recovered_root_invalid")
        ids = {
            name: _tree_member_id(context, owner.owner_id, canonical, canonical / name)
            for name in names
        }
        for item in old:
            represented.pop(item.logical_id, None)
            removed.add(item.logical_id)
        represented[root_id] = StorageItem(
            owner.owner_id,
            root_id,
            root,
            "included_directory",
            (config.logical_id,),
            metadata=FileMetadata(
                1, root_id, "", None, "directory", 0o700, 0, "private"
            ),
        )
        for name in names:
            path = root / name
            dependencies = (config.logical_id, root_id)
            if name == "catalog.sqlite3":
                dependencies += tuple(
                    key for member, key in ids.items() if member != name
                )
                if primary is not None:
                    dependencies += (primary.logical_id,)
            item = StorageItem(
                owner.owner_id,
                ids[name],
                path,
                "included",
                dependencies,
                metadata=FileMetadata(
                    1,
                    root_id,
                    name,
                    root_id,
                    "file",
                    0o600,
                    os.stat(path).st_mtime_ns,
                    "private",
                ),
            )
            represented[item.logical_id] = item
            additions.append((item, path))
        catalog_item = represented[ids["catalog.sqlite3"]]
        topology = {
            item.logical_id: (
                item.metadata.root_id,
                item.metadata.parent_id,
                item.metadata.relative_path,
                item.metadata.kind,
            )
            for item, _ in additions
            if item.metadata is not None
        }
        issues = owner.validate_restore_dependencies(
            catalog_item,
            catalog,
            {item.logical_id: path for item, path in additions},
            topology=topology,
        )
        if issues:
            raise ValueError(issues[0])
    return (
        replace(inventory, items=tuple(represented.values())),
        [(item, path) for item, path in staged if item.logical_id not in removed]
        + additions,
        (
            f"Temporary files retained as recovered assets: {retained}",
            f"Unavailable temporary references: {unavailable}",
            f"Temporary files kept deleted: {kept_deleted}",
        ),
    )


class RecoveredMedia:
    """A profile-scoped catalog; source identities never select file names."""

    is_memory_db = False

    def __init__(self, root: Path):
        self.db_path = lexical_path(root) / "catalog.sqlite3"
        result = secure_private_directory(
            self.root, create=True, application_owned=True
        )
        if not result.verified_private:
            raise ValueError("recovered_media_privacy_unverified")
        with self._connection() as connection:
            migrate(connection)
            issues = _validate_sqlite(connection, (1,), SCHEMAS)
            if issues:
                raise ValueError(issues[0])
        self.recover()

    @property
    def root(self):
        return self.db_path.parent

    @contextmanager
    def _connection(self, *, must_exist=False, expected_identity=None):
        _core_access(self)
        with closing(
            connect_private_sqlite(
                "recovered.media",
                self.db_path,
                must_exist=must_exist,
                expected_identity=expected_identity,
            )
        ) as connection:
            _register_core_connection(self, connection)
            connection.execute("PRAGMA foreign_keys=ON")
            yield connection

    def _path(self, asset_id):
        if type(asset_id) is not str or not _ASSET_ID.fullmatch(asset_id):
            raise ValueError("invalid_recovered_asset_id")
        return self.root / (asset_id + ".payload")

    def retain(
        self, source: Path, *, profile: str, message: str, slug: str, media_type: str
    ) -> str:
        identity = _identity(profile, message, slug, media_type)
        with self._connection() as connection:
            payload = _read(source)
            digest = hashlib.sha256(payload).hexdigest()
            row = connection.execute(
                "SELECT a.asset_id,a.digest,a.size,a.state FROM refs r JOIN assets a USING(asset_id) WHERE profile=? AND message=? AND slug=? AND r.media_type=?",
                identity,
            ).fetchone()
            if row:
                if row[1:3] != (digest, len(payload)) or row[3] == "deleted":
                    raise ValueError("recovered_reference_collision")
                asset_id = row[0]
                if row[3] == "ready":
                    if self._resolve(connection, asset_id)[0] != "ready":
                        raise ValueError("recovered_payload_missing")
                    return asset_id
            else:
                asset_id = uuid.uuid4().hex
                if self._path(asset_id).exists():
                    raise FileExistsError("recovered_asset_id_collision")
                with connection:
                    connection.execute(
                        "INSERT INTO assets VALUES (?,?,?,?, 'pending')",
                        (asset_id, digest, len(payload), media_type),
                    )
                    connection.execute(
                        "INSERT INTO refs VALUES (?,?,?,?,?)", identity + (asset_id,)
                    )
                    connection.execute(
                        "INSERT INTO operations VALUES (?, 'retain')", (asset_id,)
                    )
            connection.execute("BEGIN IMMEDIATE")
            try:
                if connection.execute(
                    "SELECT state FROM assets WHERE asset_id=?", (asset_id,)
                ).fetchone() != ("pending",):
                    raise ValueError("recovered_operation_changed")
                destination = self._path(asset_id)
                if destination.exists() or destination.is_symlink():
                    try:
                        matches = _read(destination) == payload
                    except (OSError, ValueError):
                        matches = False
                    if not matches:
                        raise ValueError("recovered_payload_collision")
                else:
                    result = atomic_private_write_bytes(destination, payload)
                    if not result.verified_private:
                        raise ValueError("recovered_media_privacy_unverified")
                self._finish_retain(connection, asset_id)
            finally:
                connection.rollback()
            return asset_id

    def _finish_retain(self, connection, asset_id):
        row = connection.execute(
            "SELECT digest,size,state FROM assets WHERE asset_id=?", (asset_id,)
        ).fetchone()
        if row is None or row[2] != "pending":
            raise ValueError("recovered_operation_changed")
        payload = _read(self._path(asset_id))
        if (hashlib.sha256(payload).hexdigest(), len(payload)) != row[:2]:
            raise ValueError("recovered_payload_missing")
        with connection:
            changed = connection.execute(
                "UPDATE assets SET state='ready' WHERE asset_id=? AND state='pending'",
                (asset_id,),
            ).rowcount
            if changed != 1:
                raise ValueError("recovered_operation_changed")
            connection.execute(
                "DELETE FROM operations WHERE asset_id=? AND kind='retain'", (asset_id,)
            )

    @staticmethod
    def _valid_tombstone(connection, asset_id):
        if connection.execute(
            "SELECT state FROM assets WHERE asset_id=?", (asset_id,)
        ).fetchone() != ("deleted",):
            return False
        row = connection.execute(
            "SELECT version,references_json FROM tombstones WHERE asset_id=?",
            (asset_id,),
        ).fetchone()
        if row is None or row[0] != 1:
            return False
        try:
            references = json.loads(row[1])
            current = [
                list(row)
                for row in connection.execute(
                    "SELECT profile,message,slug,media_type FROM refs WHERE asset_id=? ORDER BY profile,message,slug,media_type",
                    (asset_id,),
                )
            ]
            return type(references) is list and references == current
        except (TypeError, ValueError):
            return False

    def _resolve(self, connection, asset_id):
        path = self._path(asset_id)
        row = connection.execute(
            "SELECT digest,size,state FROM assets WHERE asset_id=?", (asset_id,)
        ).fetchone()
        if row is None:
            return "unknown", None
        if row[2] == "deleted":
            return (
                ("deleted", None)
                if self._valid_tombstone(connection, asset_id)
                else ("missing", None)
            )
        if row[2] != "ready":
            return "missing", None
        try:
            payload = _read(path)
        except (OSError, ValueError):
            return "missing", None
        if (hashlib.sha256(payload).hexdigest(), len(payload)) != row[:2]:
            return "missing", None
        return "ready", path

    def resolve(self, asset_id: str) -> tuple[str, Path | None]:
        with self._connection() as connection:
            return self._resolve(connection, asset_id)

    def resolve_reference(
        self, *, profile: str, message: str, slug: str, media_type: str
    ):
        identity = _identity(profile, message, slug, media_type)
        with self._connection() as connection:
            row = connection.execute(
                "SELECT asset_id FROM refs WHERE profile=? AND message=? AND slug=? AND media_type=?",
                identity,
            ).fetchone()
            return self._resolve(connection, row[0]) if row else ("unknown", None)

    def add_reference(self, asset_id, *, profile, message, slug, media_type):
        identity = _identity(profile, message, slug, media_type)
        with self._connection() as connection, connection:
            connection.execute("BEGIN IMMEDIATE")
            row = connection.execute(
                "SELECT media_type,state FROM assets WHERE asset_id=?", (asset_id,)
            ).fetchone()
            if row != (media_type, "ready"):
                raise ValueError("recovered_asset_not_ready")
            connection.execute(
                "INSERT INTO refs VALUES (?,?,?,?,?)", identity + (asset_id,)
            )

    def delete(self, asset_id: str, *, review=None) -> None:
        self._path(asset_id)
        expected = (
            _review_source(self, asset_id, review) if review is not None else None
        )
        with self._connection(
            must_exist=review is not None, expected_identity=expected
        ) as connection:
            with connection:
                connection.execute("BEGIN IMMEDIATE")
                if review is not None:
                    _compare_review(self, connection, review)
                if connection.execute(
                    "SELECT 1 FROM recovery_holds WHERE asset_id=?", (asset_id,)
                ).fetchone():
                    raise ValueError("recovered_asset_held")
                row = connection.execute(
                    "SELECT state FROM assets WHERE asset_id=?", (asset_id,)
                ).fetchone()
                if row is None:
                    raise KeyError(asset_id)
                if row[0] != "deleted":
                    references = list(
                        connection.execute(
                            "SELECT profile,message,slug,media_type FROM refs WHERE asset_id=? ORDER BY profile,message,slug,media_type",
                            (asset_id,),
                        )
                    )
                    connection.execute(
                        "INSERT INTO tombstones VALUES (?,1,?)",
                        (asset_id, json.dumps(references)),
                    )
                    connection.execute(
                        "UPDATE assets SET state='deleted' WHERE asset_id=?",
                        (asset_id,),
                    )
                    connection.execute(
                        "INSERT OR REPLACE INTO operations VALUES (?,'delete')",
                        (asset_id,),
                    )
            self._finish_delete(connection, asset_id)

    def _finish_delete(self, connection, asset_id):
        if not self._valid_tombstone(connection, asset_id):
            raise ValueError("invalid_recovered_tombstone")
        operation = connection.execute(
            "SELECT kind FROM operations WHERE asset_id=?", (asset_id,)
        ).fetchone()
        if operation is None:
            return  # Completed, validated deletion is idempotent.
        if operation != ("delete",):
            raise ValueError("invalid_recovered_tombstone")
        path = self._path(asset_id)
        parent, leaf = _open_verified_parent(path, missing_leaf_allowed=True)
        try:
            try:
                before = os.stat(leaf, dir_fd=parent, follow_symlinks=False)
                expected = connection.execute(
                    "SELECT digest,size FROM assets WHERE asset_id=?", (asset_id,)
                ).fetchone()
                payload = _read(path)
                after = os.stat(leaf, dir_fd=parent, follow_symlinks=False)
                if (before.st_dev, before.st_ino) != (after.st_dev, after.st_ino) or (
                    hashlib.sha256(payload).hexdigest(),
                    len(payload),
                ) != expected:
                    raise ValueError("recovered_payload_replacement")
                os.unlink(leaf, dir_fd=parent)
            except FileNotFoundError:
                pass
            os.fsync(parent)
        finally:
            os.close(parent)
        with connection:
            connection.execute(
                "DELETE FROM operations WHERE asset_id=? AND kind='delete'", (asset_id,)
            )

    def recover(self):
        """Finish only catalog-journaled operations; never sweep by age/name."""
        with self._connection() as connection:
            for asset_id, kind in connection.execute(
                "SELECT asset_id,kind FROM operations"
            ).fetchall():
                if kind == "delete":
                    self._finish_delete(connection, asset_id)
                else:
                    try:
                        self._finish_retain(connection, asset_id)
                    except (OSError, ValueError):
                        # Required unpublished bytes remain an actionable missing
                        # operation; they are never silently reclassified deleted.
                        continue

    def recovery_adapter(self):
        return _RecoveredAdapter(self.root)

    def hold(self, asset_id, hold_id):
        if type(hold_id) is not str or not hold_id:
            raise ValueError("invalid_recovery_hold")
        with self._connection() as connection, connection:
            connection.execute("BEGIN IMMEDIATE")
            if self._resolve(connection, asset_id)[0] != "ready":
                raise ValueError("recovered_asset_not_ready")
            connection.execute(
                "INSERT INTO recovery_holds VALUES (?,?)", (asset_id, hold_id)
            )

    def release_hold(self, asset_id, hold_id):
        with self._connection() as connection, connection:
            connection.execute(
                "DELETE FROM recovery_holds WHERE asset_id=? AND hold_id=?",
                (asset_id, hold_id),
            )

    def release_reference(self, *, profile, message, slug, media_type):
        identity = _identity(profile, message, slug, media_type)
        with self._connection() as connection, connection:
            connection.execute("BEGIN IMMEDIATE")
            _release_reference(connection, identity)

    def cleanup_orphan(self, asset_id, *, review=None):
        """Explicit cleanup only, with a fresh transactional reference/hold check."""
        expected = (
            _review_source(self, asset_id, review) if review is not None else None
        )
        with self._connection(
            must_exist=review is not None, expected_identity=expected
        ) as connection:
            connection.execute("BEGIN IMMEDIATE")
            try:
                if review is not None:
                    _compare_review(self, connection, review)
                if connection.execute(
                    "SELECT 1 FROM refs WHERE asset_id=? UNION ALL SELECT 1 FROM recovery_holds WHERE asset_id=?",
                    (asset_id, asset_id),
                ).fetchone():
                    return False
                if not connection.execute(
                    "SELECT 1 FROM assets WHERE asset_id=?", (asset_id,)
                ).fetchone():
                    return False
                connection.execute(
                    "INSERT OR IGNORE INTO tombstones VALUES (?,1,'[]')", (asset_id,)
                )
                connection.execute(
                    "UPDATE assets SET state='deleted' WHERE asset_id=?", (asset_id,)
                )
                connection.execute(
                    "INSERT OR REPLACE INTO operations VALUES (?,'delete')", (asset_id,)
                )
                connection.commit()
                self._finish_delete(connection, asset_id)
                return True
            finally:
                connection.rollback()


def _release_reference(connection, identity):
    """One owner transaction updates both the reference and any deletion receipt."""
    row = connection.execute(
        "SELECT asset_id FROM refs WHERE profile=? AND message=? AND slug=? AND media_type=?",
        identity,
    ).fetchone()
    if row is None:
        return
    asset_id = row[0]
    connection.execute(
        "DELETE FROM refs WHERE profile=? AND message=? AND slug=? AND media_type=?",
        identity,
    )
    if connection.execute(
        "SELECT 1 FROM tombstones WHERE asset_id=?", (asset_id,)
    ).fetchone():
        remaining = list(
            connection.execute(
                "SELECT profile,message,slug,media_type FROM refs WHERE asset_id=? ORDER BY profile,message,slug,media_type",
                (asset_id,),
            )
        )
        connection.execute(
            "UPDATE tombstones SET references_json=? WHERE asset_id=?",
            (json.dumps(remaining), asset_id),
        )


@dataclass(frozen=True)
class RecoveredAssetDetails:
    """Catalog facts; size is the recorded payload size, not measured disk use."""

    asset_id: str
    digest: str
    size: int
    media_type: str
    state: str
    reference_count: int
    hold_count: int

    @property
    def orphan_eligible(self) -> bool:
        return (
            self.state == "ready" and not self.reference_count and not self.hold_count
        )


@dataclass(frozen=True)
class RecoveredMediaDetails:
    """One bounded, consistently observed page of an existing catalog."""

    root: Path
    assets: tuple[RecoveredAssetDetails, ...]
    total: int
    offset: int
    has_more: bool


@dataclass(frozen=True)
class RecoveredAssetReview:
    """Exact selected owner identity and effects for a deliberate action."""

    root: Path
    root_identity: tuple[int, ...]
    catalog_identity: tuple[int, ...]
    asset: RecoveredAssetDetails
    references: tuple[tuple[str, str, str, str], ...]
    holds: tuple[str, ...]


def _existing_store(root):
    # Passive inspection must not create/migrate the catalog or replay journals.
    store = object.__new__(RecoveredMedia)
    store.db_path = lexical_path(root) / "catalog.sqlite3"
    return store


def _native_identity(info):
    return (info.st_dev, info.st_ino, info.st_mode, info.st_uid, info.st_nlink)


def _catalog_identity(store):
    parent, leaf = _open_verified_parent(store.db_path, missing_leaf_allowed=False)
    try:
        root = os.fstat(parent)
        catalog = os.stat(leaf, dir_fd=parent, follow_symlinks=False)
        if (
            root.st_uid != os.geteuid()
            or stat.S_IMODE(root.st_mode) & 0o077
            or not stat.S_ISREG(catalog.st_mode)
            or catalog.st_nlink != 1
            or catalog.st_uid != os.geteuid()
            or stat.S_IMODE(catalog.st_mode) != 0o600
        ):
            raise ValueError("recovered_media_privacy_unverified")
        return _native_identity(root), _native_identity(catalog), catalog
    finally:
        os.close(parent)


def _details(connection, store, asset_id):
    if type(asset_id) is not str or not _ASSET_ID.fullmatch(asset_id):
        raise ValueError("invalid_recovered_asset")
    row = connection.execute(
        "SELECT substr(digest,1,65),size,substr(media_type,1,4097),state FROM assets WHERE asset_id=?",
        (asset_id,),
    ).fetchone()
    if row is None:
        raise KeyError(asset_id)
    digest, size, media_type, state = row
    if (
        type(digest) is not str
        or re.fullmatch(r"[0-9a-f]{64}", digest) is None
        or type(size) is not int
        or not 0 <= size <= MAX_PAYLOAD_BYTES
        or type(media_type) is not str
        or len(media_type) > 4096
        or not media_type.startswith(("image/", "video/"))
        or state not in {"pending", "ready", "deleted"}
    ):
        raise ValueError("invalid_recovered_asset")
    refs = connection.execute(
        "SELECT count(*) FROM refs WHERE asset_id=?", (asset_id,)
    ).fetchone()[0]
    holds = connection.execute(
        "SELECT count(*) FROM recovery_holds WHERE asset_id=?", (asset_id,)
    ).fetchone()[0]
    if state == "deleted":
        length = connection.execute(
            "SELECT length(references_json) FROM tombstones WHERE asset_id=?",
            (asset_id,),
        ).fetchone()
        if refs > 1000 or length is None or length[0] > 16 * 1024**2:
            raise ValueError("recovered_details_limit")
        if not store._valid_tombstone(connection, asset_id):
            raise ValueError("invalid_recovered_tombstone")
    return RecoveredAssetDetails(asset_id, digest, size, media_type, state, refs, holds)


def _asset_review(store, connection, asset_id):
    asset = _details(connection, store, asset_id)
    if asset.reference_count > 1000 or asset.hold_count > 1000:
        raise ValueError("recovered_details_limit")
    references = tuple(
        connection.execute(
            "SELECT substr(profile,1,4097),substr(message,1,4097),substr(slug,1,4097),substr(media_type,1,4097) FROM refs WHERE asset_id=? ORDER BY profile,message,slug,media_type",
            (asset_id,),
        )
    )
    holds = tuple(
        row[0]
        for row in connection.execute(
            "SELECT substr(hold_id,1,4097) FROM recovery_holds WHERE asset_id=? ORDER BY hold_id",
            (asset_id,),
        )
    )
    for reference in references:
        _identity(*reference)
    if any(type(hold) is not str or not hold or len(hold) > 4096 for hold in holds):
        raise ValueError("invalid_recovery_hold")
    root, catalog, _ = _catalog_identity(store)
    return RecoveredAssetReview(store.root, root, catalog, asset, references, holds)


@contextmanager
def _inspect_catalog(store):
    root, catalog, info = _catalog_identity(store)
    with store._connection(must_exist=True, expected_identity=info) as connection:
        connection.execute("PRAGMA query_only=ON")
        connection.execute("BEGIN")
        issues = _validate_sqlite(connection, (1,), SCHEMAS)
        if issues:
            raise ValueError(issues[0])
        yield connection
        if _catalog_identity(store)[:2] != (root, catalog):
            raise ValueError("recovered_review_changed")


def list_recovered_media(root: Path, *, limit: int = 50, offset: int = 0):
    """List existing catalog metadata without payload reads or owner startup."""
    if (
        type(limit) is not int
        or not 1 <= limit <= 100
        or type(offset) is not int
        or offset < 0
    ):
        raise ValueError("recovered_details_limit")
    store = _existing_store(root)
    parent, leaf = _open_verified_parent(store.root, missing_leaf_allowed=False)
    try:
        try:
            info = os.stat(leaf, dir_fd=parent, follow_symlinks=False)
        except FileNotFoundError:
            return None
        if (
            not stat.S_ISDIR(info.st_mode)
            or info.st_uid != os.geteuid()
            or stat.S_IMODE(info.st_mode) & 0o077
        ):
            raise ValueError("recovered_media_privacy_unverified")
    finally:
        os.close(parent)
    try:
        os.stat(store.db_path, follow_symlinks=False)
    except FileNotFoundError:
        return None
    with _inspect_catalog(store) as connection:
        total = connection.execute("SELECT count(*) FROM assets").fetchone()[0]
        ids = connection.execute(
            "SELECT substr(asset_id,1,33) FROM assets ORDER BY asset_id LIMIT ? OFFSET ?",
            (limit, offset),
        )
        assets = tuple(_details(connection, store, row[0]) for row in ids)
        return RecoveredMediaDetails(
            store.root, assets, total, offset, offset + len(assets) < total
        )


def review_recovered_asset(root: Path, asset_id: str) -> RecoveredAssetReview:
    """Review all affected reference identities and holds without reading media."""
    store = _existing_store(root)
    store._path(asset_id)
    with _inspect_catalog(store) as connection:
        return _asset_review(store, connection, asset_id)


def _review_source(store, asset_id, review):
    if (
        type(review) is not RecoveredAssetReview
        or review.root != store.root
        or review.asset.asset_id != asset_id
    ):
        raise ValueError("recovered_review_changed")
    root, catalog, info = _catalog_identity(store)
    if (root, catalog) != (review.root_identity, review.catalog_identity):
        raise ValueError("recovered_review_changed")
    return info


def _compare_review(store, connection, review):
    issues = _validate_sqlite(connection, (1,), SCHEMAS)
    if issues:
        raise ValueError(issues[0])
    if _asset_review(store, connection, review.asset.asset_id) != review:
        raise ValueError("recovered_review_changed")


def delete_reviewed_asset(review: RecoveredAssetReview) -> None:
    """Perform an explicitly reviewed deletion through the existing journal."""
    if type(review) is not RecoveredAssetReview:
        raise ValueError("recovered_review_changed")
    _existing_store(review.root).delete(review.asset.asset_id, review=review)


def cleanup_reviewed_asset(review: RecoveredAssetReview) -> bool:
    """Recheck a reviewed orphan, retaining all existing reference/hold checks."""
    if type(review) is not RecoveredAssetReview:
        raise ValueError("recovered_review_changed")
    return _existing_store(review.root).cleanup_orphan(
        review.asset.asset_id, review=review
    )


class _RecoveredAdapter:
    """Installed catalog policy plus its explicit generated-name dependencies."""

    owner_id = "recovered.media"
    activation_required = True

    def __init__(self, root=None):
        self.root = root

    def schema_policy(self):
        return schema_policy()

    def restore_role(self, item):
        """Classify only installed catalog/generated payload archive topology."""
        meta = item.metadata
        if item.owner != self.owner_id or meta is None:
            raise ValueError("invalid_dependency_context")
        if (
            meta.kind == "directory"
            and meta.parent_id is None
            and meta.relative_path in {"", "."}
        ):
            return "directory"
        if meta.kind == "file" and meta.relative_path == "catalog.sqlite3":
            return "sqlite"
        name = meta.relative_path
        if (
            meta.kind == "file"
            and name.endswith(".payload")
            and _ASSET_ID.fullmatch(name[:-8])
        ):
            return "file"
        raise ValueError("invalid_recovered_role")

    def validate_restore(self, item, candidate):
        """Keep opaque payload bytes out of the SQLite inspection route."""
        from tldw_chatbook.DB.private_sqlite import open_recovery_validation

        from .recovery_files import _RawDeclaration

        role = self.restore_role(item)
        if role == "sqlite":
            try:
                with open_recovery_validation(
                    self.owner_id, candidate, writable=False
                ) as connection:
                    return self._validate_connection(connection)
            except (OSError, ValueError, TypeError, sqlite3.Error):
                return ("recovered_validation_unavailable",)
        if role == "file":
            return _RawDeclaration(self.owner_id, max_bytes=MAX_PAYLOAD_BYTES).validate(
                candidate
            )
        return ()

    def relocate_restore(self, item, candidate, mapping):
        """Preserve source identities and add the selected profile's aliases."""
        from tldw_chatbook.DB.private_sqlite import open_recovery_validation

        from .sqlite_validation import _Restrictions

        issues = self.validate_restore(item, candidate)
        if issues:
            raise ValueError(issues[0])
        if self.restore_role(item) != "sqlite":
            return  # Generated payload locators remain relative and unchanged.

        from .profile_paths import lexical_path as selected_path

        parts = item.logical_id.split(":")
        if len(parts) < 3 or parts[0] != "profile" or parts[2] != self.owner_id:
            raise ValueError("recovered_profile_mapping_required")
        config_id = f"profile:{parts[1]}:config"
        destination = mapping.get(config_id)
        if config_id not in item.dependencies or not isinstance(destination, Path):
            raise ValueError("recovered_profile_mapping_required")
        profile = hashlib.sha256(str(selected_path(destination)).encode()).hexdigest()[
            :24
        ]
        with (
            open_recovery_validation(
                self.owner_id, candidate, writable=True
            ) as connection,
            connection,
        ):
            restrictions = _Restrictions(connection)
            connection.set_authorizer(
                _recovered_alias_authorizer(restrictions.authorize)
            )
            connection.execute("BEGIN IMMEDIATE")
            # Validate again on the same connection that owns all alias changes.
            issues = self._validate_connection(connection)
            if issues:
                raise ValueError(issues[0])
            references = connection.execute(
                "SELECT r.message,r.slug,r.media_type,r.asset_id,a.state "
                "FROM refs r JOIN assets a USING(asset_id) WHERE r.profile=? "
                "ORDER BY r.message,r.slug,r.media_type",
                (parts[1],),
            ).fetchall()
            deleted = set()
            for message, slug, media_type, asset_id, state in references:
                identity = (profile, message, slug, media_type)
                existing = connection.execute(
                    "SELECT asset_id FROM refs WHERE profile=? AND message=? AND slug=? AND media_type=?",
                    identity,
                ).fetchone()
                if existing is not None and existing != (asset_id,):
                    raise ValueError("recovered_reference_collision")
                if existing is None:
                    connection.execute(
                        "INSERT INTO refs VALUES (?,?,?,?,?)", identity + (asset_id,)
                    )
                    if state == "deleted":
                        deleted.add(asset_id)
            for asset_id in sorted(deleted):
                references = list(
                    connection.execute(
                        "SELECT profile,message,slug,media_type FROM refs WHERE asset_id=? ORDER BY profile,message,slug,media_type",
                        (asset_id,),
                    )
                )
                connection.execute(
                    "UPDATE tombstones SET references_json=? WHERE asset_id=?",
                    (json.dumps(references), asset_id),
                )
            issues = self._validate_connection(connection)
            if issues:
                raise ValueError(issues[0])

    def validate_restore_dependencies(self, item, candidate, candidates, *, topology):
        """Match ready catalog entries to declared archive-local payload IDs."""
        from tldw_chatbook.DB.private_sqlite import open_recovery_validation

        from .storage_admission import _digest_recovery_file

        meta = item.metadata
        if meta is None or topology.get(item.logical_id) != (
            meta.root_id,
            meta.parent_id,
            meta.relative_path,
            meta.kind,
        ):
            return ("invalid_dependency_context",)
        try:
            if self.restore_role(item) != "sqlite":
                return ()
            issues = self.validate_restore(item, candidate)
            if issues:
                return issues
            located = {}
            for key in set(item.dependencies) & candidates.keys() & topology.keys():
                root, _parent, relative, kind = topology[key]
                if root == meta.root_id and kind == "file":
                    located.setdefault(relative, []).append(key)
            with open_recovery_validation(
                self.owner_id, candidate, writable=False
            ) as connection:
                for asset_id, digest, size in connection.execute(
                    "SELECT asset_id,digest,size FROM assets WHERE state='ready'"
                ):
                    keys = located.get(asset_id + ".payload", ())
                    if len(keys) != 1 or _digest_recovery_file(
                        self.owner_id, candidates[keys[0]], max_bytes=MAX_PAYLOAD_BYTES
                    ) != (size, digest):
                        return ("recovered_payload_missing",)
            return ()
        except (OSError, ValueError, RuntimeError, sqlite3.Error):
            return ("recovered_payload_missing",)

    def validate(self, candidate):
        try:
            with closing(
                connect_private_sqlite(
                    "recovery.recovered_media", candidate, read_only=True
                )
            ) as connection:
                return self._validate_connection(connection)
        except (OSError, ValueError, TypeError, sqlite3.Error):
            return ("recovered_validation_unavailable",)

    @staticmethod
    def _validate_connection(connection):
        """Validate installed schema/domain on the caller-owned connection."""
        issues = _validate_sqlite(connection, (1,), SCHEMAS)
        if issues:
            return issues
        if connection.execute("SELECT 1 FROM operations").fetchone():
            return ("recovered_operation_pending",)
        if connection.execute(
            "SELECT 1 FROM refs r JOIN assets a USING(asset_id) WHERE r.media_type != a.media_type"
        ).fetchone():
            return ("invalid_recovered_reference",)
        if connection.execute(
            "SELECT 1 FROM tombstones t JOIN assets a USING(asset_id) WHERE a.state != 'deleted'"
        ).fetchone():
            return ("invalid_recovered_tombstone",)
        for asset_id, digest, size, media_type, state in connection.execute(
            "SELECT * FROM assets"
        ):
            if (
                not _ASSET_ID.fullmatch(asset_id)
                or not re.fullmatch(r"[0-9a-f]{64}", digest)
                or type(size) is not int
                or not 0 <= size <= MAX_PAYLOAD_BYTES
                or not media_type.startswith(("image/", "video/"))
            ):
                return ("invalid_recovered_asset",)
            if state == "pending":
                return ("recovered_operation_pending",)
            if state == "deleted" and not RecoveredMedia._valid_tombstone(
                connection, asset_id
            ):
                return ("invalid_recovered_tombstone",)
        for profile, message, slug, media_type in connection.execute(
            "SELECT profile,message,slug,media_type FROM refs"
        ):
            _identity(profile, message, slug, media_type)
        return ()

    def discover(self, config):
        from dataclasses import replace

        from .models import StorageItem, discovery_context, storage_logical_id
        from .profile_paths import user_data_dir
        from .recovery_files import _RawDeclaration

        root = self.root or user_data_dir(config) / "recovered_media"
        context = discovery_context(config)
        catalog = root / "catalog.sqlite3"
        entries = _RawDeclaration(self.owner_id)._tree(config, root)
        if not root.exists():
            return entries
        issues = self.validate(catalog)
        if issues:
            return (
                StorageItem(
                    self.owner_id,
                    storage_logical_id(context, self.owner_id),
                    catalog,
                    "unavailable",
                    (),
                ),
            )
        with closing(
            connect_private_sqlite("recovery.recovered_media", catalog, read_only=True)
        ) as connection:
            assets = {
                asset_id + ".payload": (digest, size)
                for asset_id, digest, size in connection.execute(
                    "SELECT asset_id,digest,size FROM assets WHERE state='ready'"
                )
            }
        wanted = {"catalog.sqlite3", *assets}
        selected = []
        found = set()
        for item in entries:
            if item.path == root:
                selected.append(item)
            elif item.path.name in wanted and item.path.parent == root:
                found.add(item.path.name)
                if item.path.name in assets:
                    try:
                        from .storage_admission import _consume_recovery_file

                        size, digest = _consume_recovery_file(
                            self.owner_id,
                            item.path,
                            max_bytes=MAX_PAYLOAD_BYTES,
                            collect=False,
                            digest=True,
                            private=True,
                        )
                        valid = (digest, size) == assets[item.path.name]
                    except (OSError, ValueError):
                        valid = False
                    if not valid:
                        item = replace(item, status="missing_required")
                selected.append(item)
            elif item.path.name not in {
                "catalog.sqlite3-wal",
                "catalog.sqlite3-shm",
                "catalog.sqlite3-journal",
            }:
                # Unknown files are evidence, never inferred deletions or TTL junk.
                selected.append(replace(item, status="unsupported"))
        for missing in wanted - found:
            selected.append(
                StorageItem(
                    self.owner_id,
                    storage_logical_id(context, self.owner_id, missing),
                    root / missing,
                    "missing_required",
                    (),
                )
            )
        dependencies = tuple(
            item.logical_id for item in selected if item.path != catalog
        )
        return tuple(
            replace(
                item,
                dependencies=tuple(dict.fromkeys(item.dependencies + dependencies)),
            )
            if item.path == catalog
            else item
            for item in selected
        )

    def capture(self, item, destination, cancel):
        from tldw_chatbook.DB.private_sqlite import copy_private_sqlite
        from tldw_chatbook.DB.recovery_sqlite import _checked_capture

        from .recovery_files import _RawDeclaration

        if item.path is not None and item.path.name == "catalog.sqlite3":
            with _checked_capture(
                self.owner_id, item, destination, cancel, self.validate
            ) as guard:
                copy_private_sqlite(
                    "recovery.recovered_media",
                    item.path,
                    destination,
                    progress_guard=guard,
                )
        else:
            _RawDeclaration(self.owner_id, max_bytes=MAX_PAYLOAD_BYTES).capture(
                item, destination, cancel
            )

    def relocate(self, candidate, mapping):
        # Payload locators are generated relative names. Stable source identities,
        # references, tombstones and recovery holds remain evidence after a move.
        issues = self.validate(candidate)
        if issues:
            raise ValueError(issues[0])

    def validate_dependencies(self, item, candidate, candidates):
        """Require every registered ready payload, independently of its name."""
        from .models import DiscoveryContext
        from .recovery_files import _tree_member_id
        from .storage_admission import _digest_recovery_file

        issues = self.validate(candidate)
        if issues:
            return issues
        parts = item.logical_id.split(":")
        if (
            item.owner != self.owner_id
            or item.path is None
            or len(parts) < 3
            or parts[0] != "profile"
        ):
            return ("invalid_dependency_context",)
        context = DiscoveryContext(Path("/historical-selector-not-opened"), parts[1])
        try:
            with closing(
                connect_private_sqlite(
                    "recovery.recovered_media", candidate, read_only=True
                )
            ) as connection:
                for asset_id, digest, size in connection.execute(
                    "SELECT asset_id,digest,size FROM assets WHERE state='ready'"
                ):
                    key = _tree_member_id(
                        context,
                        self.owner_id,
                        item.path.parent,
                        item.path.parent / (asset_id + ".payload"),
                    )
                    if key not in item.dependencies or key not in candidates:
                        return ("recovered_payload_missing",)
                    if _digest_recovery_file(
                        self.owner_id, candidates[key], max_bytes=MAX_PAYLOAD_BYTES
                    ) != (size, digest):
                        return ("recovered_payload_missing",)
            return ()
        except (OSError, ValueError, sqlite3.Error):
            return ("recovered_payload_missing",)


def recovery_adapters():
    """Declare the baseline owner without opening any runtime store."""
    return (_RecoveredAdapter(),)


def current_profile_id():
    """Use the same selector identity as recovery inventory discovery."""
    from .profile_paths import effective_config_path

    return hashlib.sha256(str(effective_config_path()).encode()).hexdigest()[:24]


def message_image_metadata(root, profile, messages):
    """Read existing reference metadata in bounded batches, without payload IO.

    Readers do not migrate or replay publication journals. The ordinary owner
    connection still binds catalog admission and retires on this worker thread.
    """
    path = lexical_path(root) / "catalog.sqlite3"
    if not path.exists():
        return {}
    store = object.__new__(RecoveredMedia)
    store.db_path = path
    found = {}
    with store._connection() as connection:
        issues = _validate_sqlite(connection, (1,), SCHEMAS)
        if issues:
            raise ValueError(issues[0])
        for start in range(0, len(messages), 200):
            batch = messages[start : start + 200]
            slots = ",".join("?" for _ in batch)
            rows = connection.execute(
                "SELECT r.message,a.asset_id,a.digest,a.size,a.state,r.media_type "
                "FROM refs r JOIN assets a ON a.asset_id=r.asset_id "
                f"WHERE r.profile=? AND r.message IN ({slots}) "  # nosec B608: placeholders only
                "AND r.media_type LIKE 'image/%'",
                (profile, *batch),
            ).fetchall()
            for message, asset, digest, size, state, media_type in rows:
                status = state if state in {"ready", "deleted"} else "missing"
                if status == "deleted" and not store._valid_tombstone(
                    connection, asset
                ):
                    status = "missing"
                found[message] = (
                    ("missing", None, None, None, None)
                    if message in found
                    else (status, asset, digest, size, media_type)
                )
    return found


def read_message_image_payload(root, metadata):
    """Read and verify the selected ready payload exactly once on a worker."""
    status, asset, digest, size, _media_type = metadata
    if status != "ready" or not _ASSET_ID.fullmatch(asset):
        raise ValueError("invalid_recovered_image")
    payload = _read(lexical_path(root) / (asset + ".payload"))
    if (hashlib.sha256(payload).hexdigest(), len(payload)) != (digest, size):
        raise ValueError("recovered_payload_mismatch")
    return payload


def resolve_message_image(message, *, root=None, profile=None):
    """Resolve the enhanced widget's single-image slot from persisted identity.

    Multiple recovered image keys cannot be inferred from a single-image widget;
    render missing rather than silently substituting one or using transient bytes.
    """
    if root is None:
        from tldw_chatbook.Utils.paths import get_user_data_dir

        root = get_user_data_dir() / "recovered_media"
    root = Path(root)
    if not (root / "catalog.sqlite3").exists():
        return "unknown", None, None
    store = RecoveredMedia(root)
    with store._connection() as connection:
        rows = connection.execute(
            "SELECT asset_id,media_type FROM refs WHERE profile=? AND message=? AND media_type LIKE 'image/%'",
            (profile or current_profile_id(), message),
        ).fetchall()
        if not rows:
            return "unknown", None, None
        if len(rows) != 1:
            return "missing", None, None
        asset_id, media_type = rows[0]
        status, path = store._resolve(connection, asset_id)
        return status, _read(path) if path else None, media_type


def message_reference_page(
    root: Path, profile: str, *, after: str = ""
) -> tuple[str, ...]:
    """Read up to 200 exact current-profile message keys without payload access."""
    _identity(profile, "page", "page", "image/png")
    if type(after) is not str or len(after) > 4096:
        raise ValueError("invalid_recovered_reference")
    if list_recovered_media(root, limit=1) is None:
        return ()
    store = _existing_store(root)
    with _inspect_catalog(store) as connection:
        rows = connection.execute(
            "SELECT DISTINCT substr(message,1,4097) FROM refs WHERE profile=? AND message>? ORDER BY message LIMIT 200",
            (profile, after),
        )
        result = tuple(row[0] for row in rows)
        for message in result:
            _identity(profile, message, "page", "image/png")
        return result


def release_message_references(
    root: Path, profile: str, message_ids: tuple[str, ...], *, expected_identity=None
) -> None:
    """Release exact committed message references, never the retained payload."""
    if type(message_ids) is not tuple or len(message_ids) > 200:
        raise ValueError("recovered_details_limit")
    for message in message_ids:
        _identity(profile, message, "release", "image/png")
    if not message_ids or list_recovered_media(root, limit=1) is None:
        return
    store = _existing_store(root)
    root_identity, catalog_identity, expected = _catalog_identity(store)
    if expected_identity is not None and expected_identity != (
        root_identity[:4],
        catalog_identity,
    ):
        raise ValueError("recovered_message_source_changed")
    with (
        store._connection(must_exist=True, expected_identity=expected) as connection,
        connection,
    ):
        connection.execute("BEGIN IMMEDIATE")
        if _catalog_identity(store)[:2] != (root_identity, catalog_identity):
            raise ValueError("recovered_message_source_changed")
        issues = _validate_sqlite(connection, (1,), SCHEMAS)
        if issues:
            raise ValueError(issues[0])
        for message in dict.fromkeys(message_ids):
            while True:
                # Exhaust this bounded SELECT before mutating its source table.
                rows = connection.execute(
                    "SELECT profile,message,substr(slug,1,4097),substr(media_type,1,4097) FROM refs WHERE profile=? AND message=? LIMIT 200",
                    (profile, message),
                ).fetchall()
                if not rows:
                    break
                for identity in rows:
                    _release_reference(connection, _identity(*identity))


def _message_catalog_identity(store):
    # APFS directory link counts change when ordinary payloads are retired.
    # The directory's native identity and the catalog's single-link identity stay bound.
    root, catalog, _ = _catalog_identity(store)
    return root[:4], catalog
